// @generated by `ruskel-snapshot`; do not edit.

pub mod edev {
    //! Script-first MCP launcher for eguidev.

    /// Errors returned by the edev launcher.
    pub enum EdevError {
        #[error("invalid arguments: {0}")]
        /// Argument parsing error.
        InvalidArgs(String),
        #[error("mcp error: {0}")]
        /// MCP transport error.
        Mcp(tmcp::Error),
        #[error("io error: {0}")]
        /// IO error.
        Io(std_io::Error),
        #[error("app start failed: {0}")]
        /// Application startup error.
        AppStart(String),
        #[error("smoke failed: {0}")]
        /// Smoke suite failure.
        SmokeFailed(String),
        #[error("record failed: {0}")]
        /// Recording failure.
        RecordFailed(String),
        #[error("eval failed: {0}")]
        /// One-shot script evaluation failure.
        EvalFailed(String),
        #[error("fixture failed: {0}")]
        /// Fixture operation failure.
        FixtureFailed(String),
        #[error("instance registry error: {0}")]
        /// Instance registry error.
        InstanceRegistry(String),
        #[error("app shutdown was forced: {0}")]
        /// Managed app teardown required forced process cleanup.
        ForcedShutdown(String),
    }

    /// Run the Eguidev launcher on stdio.
    pub async fn run() -> Result<(), EdevError> {}

    impl Debug for EdevError {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Display for EdevError {
        fn fmt(&self, __formatter: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {}
    }

    impl Error for EdevError {
        fn source(
            &self,
        ) -> ::core::option::Option<&(dyn ::thiserror::__private19::Error + 'static)> {
        }
    }

    impl From<Error> for EdevError {
        fn from(source: McpError) -> Self {}
    }

    impl From<Error> for EdevError {
        fn from(source: std_io::Error) -> Self {}
    }
}
