// @generated by `ruskel-snapshot`; do not edit.
//
// Package: edev
// Publish: crates.io
// Declared features: default, test-app
// Binaries: edev, edev_test_app
// Workspace dependencies: eguidev, eguidev_runtime
// Workspace dependents: none

//! Script-first MCP launcher for eguidev.

use std::fmt::{Debug, Display};

/// Errors returned by the edev launcher.
#[derive(Debug, Display, std::error::Error)]
pub enum EdevError {
    /// Argument parsing error.
    #[error("invalid arguments: {0}")]
    InvalidArgs(String),
    /// MCP transport error.
    #[error("mcp error: {0}")]
    Mcp(tmcp::Error),
    /// IO error.
    #[error("io error: {0}")]
    Io(std::io::Error),
    /// Application startup error.
    #[error("app start failed: {0}")]
    AppStart(String),
    /// Smoke suite failure.
    #[error("smoke failed: {0}")]
    SmokeFailed(String),
    /// Recording failure.
    #[error("record failed: {0}")]
    RecordFailed(String),
    /// One-shot script evaluation failure.
    #[error("eval failed: {0}")]
    EvalFailed(String),
    /// Fixture operation failure.
    #[error("fixture failed: {0}")]
    FixtureFailed(String),
    /// Instance registry error.
    #[error("instance registry error: {0}")]
    InstanceRegistry(String),
    /// Managed app teardown required forced process cleanup.
    #[error("app shutdown was forced: {0}")]
    ForcedShutdown(String),
}

impl From<std::io::Error> for EdevError {}

impl From<tmcp::Error> for EdevError {}

/// Run the Eguidev launcher on stdio.
pub async fn run() -> Result<(), EdevError>;
