// @generated by `ruskel-snapshot`; do not edit.
//
// Package: eguidev_runtime
// Publish: crates.io
// Workspace dependencies: eguidev
// Workspace dependents: edev, eguidev_demo, xtask

//! Native embedded runtime for `eguidev`.
//!
//! `eguidev_runtime` attaches the in-process automation server, script
//! evaluation, screenshots, and smoke runner to an inert [`eguidev::DevMcp`]
//! handle.
//!
//! For `eframe` applications, the most reliable integration pattern is:
//!
//! - choose `eframe::Renderer::Glow` for automation runs when possible
//! - register a fixture handler with [`eguidev::DevMcp::on_fixture_runtime`] or
//!   [`eguidev::DevMcp::on_fixture_ui`]
//! - wrap every frame in [`eguidev::FrameGuard`], which registers an egui
//!   plugin on the first frame to inject input automatically
//!
//! The `wgpu` backend can exhibit idle-frame stalls in some `eframe`
//! integrations, so the demo and examples prefer `Glow`.

use std::{
    collections::BTreeMap,
    error::Error,
    fmt::{Debug, Display},
    path::PathBuf,
    time::Duration,
};

pub use eguidev::{DevMcp, Rect, ScrollAreaMeta};
use eguidev::{DevMcp, Rect, WidgetValue};
use schemars::JsonSchema;
use serde_core::{de::Deserialize, ser::Serialize};
use serde_json::Value;
use tmcp::schema::CallToolResult;
use tokio::runtime::Handle;
/// Optional loopback address used for a directly connectable app MCP server.
#[doc(hidden)]
pub const MCP_ADDR_ENV: &str = "EGUIDEV_MCP_ADDR";

/// One egui identity diagnostic from a completed viewport pass.
#[derive(Clone, Debug, Deserialize<'de>, PartialEq, Serialize)]
pub struct EguiDiagnostic {
    /// Stable diagnostic kind.
    pub kind: EguiDiagnosticKind,
    /// Diagnostic severity.
    pub severity: EguiDiagnosticSeverity,
    /// Human-readable warning text.
    pub message: String,
    /// Canonical viewport selector that produced the diagnostic.
    pub viewport_id: String,
    /// Eguidev app-wide frame counter at output completion.
    pub frame: u64,
    /// Affected rectangle when egui supplies one.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rect: Option<Rect>,
}

impl JsonSchema for EguiDiagnostic {}

/// Diagnostics retained for one script evaluation.
#[derive(Clone, Debug, Default, Deserialize<'de>, PartialEq, Serialize)]
pub struct EguiDiagnosticBatch {
    /// Retained diagnostics in journal sequence order.
    pub entries: Vec<EguiDiagnostic>,
    /// Undismissed diagnostics overwritten before they could be returned.
    pub dropped: u64,
}

impl EguiDiagnosticBatch {
    /// Return whether the batch contains no retained or dropped diagnostics.
    pub fn is_empty(&self) -> bool;
}

impl JsonSchema for EguiDiagnosticBatch {}

/// Kind of identity warning emitted by egui.
#[derive(Clone, Copy, Debug, Deserialize<'de>, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum EguiDiagnosticKind {
    /// One egui ID was used for different rectangles in one pass.
    IdClash,
    /// One rectangle changed egui ID between completed passes.
    RectChangedId,
}

impl JsonSchema for EguiDiagnosticKind {}

/// Severity assigned to an egui diagnostic.
#[derive(Clone, Copy, Debug, Deserialize<'de>, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum EguiDiagnosticSeverity {
    /// The diagnostic reports suspicious identity behavior.
    Warning,
}

impl JsonSchema for EguiDiagnosticSeverity {}

/// Fixture applied during a script evaluation.
#[derive(Clone, Debug, Deserialize<'de>, PartialEq, Serialize)]
pub struct FixtureApplication {
    /// Fixture name passed to `eguidev.fixture(...)`.
    pub name: String,
    /// Validated fixture parameters, including defaults supplied by the fixture
    /// spec.
    #[serde(default)]
    #[serde(skip_serializing_if = "BTreeMap::is_empty")]
    pub params: BTreeMap<String, WidgetValue>,
}

/// Scalar value that can be injected into the global Luau `args` table.
#[derive(Clone, Debug, Deserialize<'de>, PartialEq, Serialize)]
#[serde(untagged)]
pub enum ScriptArgValue {
    /// String-valued script arg.
    String(String),
    /// Integer-valued script arg.
    Int(i64),
    /// Floating-point script arg.
    Float(f64),
    /// Boolean-valued script arg.
    Bool(bool),
}

impl JsonSchema for ScriptArgValue {}

/// Deterministic map of script args exposed to Luau as the global `args` table.
pub type ScriptArgs = BTreeMap<String, ScriptArgValue>;

/// Assertion outcome recorded during script execution.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize)]
pub struct ScriptAssertion {
    /// Whether the assertion passed.
    pub passed: bool,
    /// Assertion message recorded by the runtime.
    pub message: String,
    /// Human-readable source location for the assertion.
    pub location: String,
}

/// One strict-check failure with a source-relative primary location.
#[derive(Clone, Debug, Display, Eq, Error, PartialEq)]
pub struct ScriptCheckError {/* private fields */}

/// Error details reported by the script runtime.
#[derive(Clone, Debug, Deserialize<'de>, PartialEq, Serialize)]
pub struct ScriptErrorInfo {
    /// Broad error category such as `parse`, `runtime`, or `assertion`.
    #[serde(rename = "type")]
    pub error_type: String,
    /// Error message presented to the caller.
    pub message: String,
    /// Optional source location for the error.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub location: Option<ScriptLocation>,
    /// Optional backtrace rendered by the script runtime.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub backtrace: Option<Vec<String>>,
    /// Optional machine-readable error code for structured tool failures.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// Optional extra error details supplied by the runtime.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub details: Option<Value>,
}

/// Options for evaluating a Luau script.
#[derive(Clone, Debug, Default, Deserialize<'de>, PartialEq, Serialize)]
pub struct ScriptEvalOptions {
    /// Optional source name used in diagnostics and error messages.
    pub source_name: Option<String>,
    /// Maximum Luau instructions before the runaway-script backstop stops
    /// evaluation.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_instructions: Option<u64>,
    /// Optional JSON object exposed to the script as the global `args` table.
    #[serde(default)]
    pub args: ScriptArgs,
    /// Named Luau modules available to this script and its dependencies.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub modules: ScriptModules,
}

impl JsonSchema for ScriptEvalOptions {}

/// Structured result of evaluating a Luau script directly against a `DevMcp`
/// instance.
#[derive(Clone, Debug, Deserialize<'de>, Serialize)]
pub struct ScriptEvalOutcome {
    /// Whether evaluation completed successfully.
    pub success: bool,
    /// Optional JSON-serializable script return value.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub value: Option<Value>,
    /// Optional metadata for images returned by the script.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub images: Option<Vec<ScriptImageInfo>>,
    /// Log lines emitted through the script `log(...)` helper.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    #[serde(default)]
    pub logs: Vec<String>,
    /// Assertion outcomes recorded during evaluation.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    #[serde(default)]
    pub assertions: Vec<ScriptAssertion>,
    /// Fixtures applied during evaluation.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    #[serde(default)]
    pub fixtures: Vec<FixtureApplication>,
    /// Timing information for the evaluation.
    pub timing: ScriptTiming,
    /// Error details when evaluation fails.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<ScriptErrorInfo>,
    /// Undismissed egui identity diagnostics produced during evaluation.
    #[serde(default)]
    #[serde(skip_serializing_if = "EguiDiagnosticBatch::is_empty")]
    pub egui_diagnostics: EguiDiagnosticBatch,
    /* private fields */
}

impl From<ScriptEvalOutcome> for CallToolResult {}

/// Request payload for the `script_eval` MCP tool.
#[derive(Clone, Debug, Deserialize<'de>, PartialEq, Serialize)]
pub struct ScriptEvalRequest {
    /// Luau source code to execute.
    pub script: String,
    /// Optional evaluation timeout in milliseconds.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub timeout_ms: Option<u64>,
    /// Optional extra evaluation options.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub options: Option<ScriptEvalOptions>,
}

impl JsonSchema for ScriptEvalRequest {}

/// Metadata for an image captured during script execution.
#[derive(Clone, Debug, Deserialize<'de>, PartialEq, Serialize)]
pub struct ScriptImageInfo {
    /// Stable image identifier assigned by the runtime.
    pub id: String,
    /// Index of the image content block in the MCP result payload.
    pub content_index: usize,
    /// Image kind such as `viewport` or `widget`.
    pub kind: String,
    /// Viewport that produced the image when known.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub viewport_id: Option<String>,
    /// Serialized widget target metadata when the image came from a widget.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub target: Option<Value>,
    /// Captured rectangle metadata when available.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rect: Option<Value>,
    /// Extra metadata attached by the runtime.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Value>,
}

/// Source location reported for a script error.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize)]
pub struct ScriptLocation {
    /// One-based line number.
    pub line: usize,
    /// One-based column number when available.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub column: Option<usize>,
}

/// Named Luau module sources available through `require` during one evaluation.
///
/// Keys are portable module paths relative to the caller-selected module root.
/// A `.luau` suffix is optional for `require`; retaining it here keeps source
/// names useful in diagnostics and failure bundles.
pub type ScriptModules = BTreeMap<String, String>;

/// Timing information for a script evaluation.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize)]
pub struct ScriptTiming {
    /// Time spent compiling the script in milliseconds.
    pub compile_ms: u64,
    /// Time spent executing the script in milliseconds.
    pub exec_ms: u64,
    /// Total wall-clock evaluation time in milliseconds.
    pub total_ms: u64,
}

/// Attach the embedded runtime to an inert `DevMcp` handle.
pub fn attach(devmcp: DevMcp) -> DevMcp;

/// Return whether this process was launched for Eguidev automation.
pub fn automation_launch() -> bool;

/// Check one tenant source against the exact checked-in public declaration.
pub fn check_script_source(source_name: &str, source: &str) -> Result<(), ScriptCheckError>;

/// Keep a background-launched app from taking focus for its whole run.
///
/// On macOS this enables the activation guard: while the automation
/// presentation is background (the default), any activation of the app that
/// was not caused by a user mouse interaction is immediately handed back to
/// the previously frontmost application. Call before the app's event loop
/// starts. On other platforms this is a no-op.
pub fn enable_background_launch_guard();

/// Evaluate a Luau script directly against this attached `DevMcp` instance.
pub async fn eval_script(
    devmcp: &DevMcp,
    script_source: &str,
    timeout_ms: Option<u64>,
    options: ScriptEvalOptions,
) -> ScriptEvalOutcome;

/// Return the checked-in Luau definitions that describe the scripting API.
pub fn script_definitions() -> &'static str;

pub mod smoke {
    //! Smoketest suite runner for Luau scripts against a live DevMCP app.

    /// Result of a single script execution.
    #[derive(Clone, Debug, PartialEq)]
    pub struct ScriptResult {
        /// One-based round index for repeated suite runs.
        pub round: u32,
        /// Forward-slash-normalized relative script path, or `<suite>` for
        /// suite-level failures.
        pub path: String,
        /// Final script status.
        pub status: ScriptStatus,
        /// Script runtime in milliseconds. Skipped scripts report `0`.
        pub elapsed_ms: u64,
        /// Failure or skip message when present.
        pub message: Option<String>,
        /// Logs emitted by the script.
        pub logs: Vec<String>,
        /// Fixtures applied during the script.
        pub fixtures: Vec<FixtureApplication>,
        /// Undismissed egui diagnostics retained by the evaluation.
        pub egui_diagnostics: EguiDiagnosticBatch,
        /// Verbose failure details from the script runtime.
        pub details: Option<String>,
    }

    /// Input passed to a caller-supplied per-script smoke executor.
    #[derive(Clone, Debug, PartialEq)]
    pub struct ScriptRunRequest {
        /// Forward-slash-normalized relative script path used for diagnostics.
        pub path: String,
        /// One-based round index for repeated suite runs.
        pub round: u32,
        /// Luau source code loaded from disk.
        pub source: String,
        /// Optional per-script timeout in milliseconds.
        pub timeout_ms: Option<u64>,
        /// Optional Luau instruction backstop.
        pub max_instructions: Option<u64>,
        /// Suite-wide args passed to the script.
        pub args: ScriptArgs,
    }

    /// Outcome for an individual smoketest script.
    #[derive(Clone, Debug, Eq, PartialEq)]
    pub enum ScriptStatus {
        /// Script completed successfully.
        Pass,
        /// Script failed or the suite hit a setup error.
        Fail,
        /// Script was skipped because the suite timed out or fail-fast triggered.
        Skip,
    }

    /// Configuration for a smoketest suite run.
    #[derive(Clone, Debug, PartialEq)]
    pub struct SuiteConfig {
        /// Directory containing `.luau` test scripts.
        pub suite_dir: PathBuf,
        /// Explicit script paths to run. Empty means discover all `.luau` files
        /// under `suite_dir` recursively in lexicographic order.
        pub scripts: Vec<PathBuf>,
        /// Discovery glob filters matched against display paths. Empty means all
        /// discovered scripts. Cannot be combined with explicit `scripts`.
        pub only: Vec<String>,
        /// Wall-clock deadline for the entire suite.
        pub suite_timeout: Duration,
        /// Per-script timeout. `None` uses the script-eval default.
        pub script_timeout: Option<Duration>,
        /// Optional Luau instruction backstop applied to every script.
        pub max_instructions: Option<u64>,
        /// Stop after the first failure.
        pub fail_fast: bool,
        /// Fail scripts that leave egui identity diagnostics undismissed.
        pub fail_on_egui_diagnostics: bool,
        /// Repetition behavior for the selected suite.
        pub run_mode: SuiteRunMode,
        /// Args passed to every script in the suite.
        pub args: ScriptArgs,
    }

    impl SuiteConfig {
        /// Apply suite-level egui diagnostic policy to one script outcome.
        pub fn apply_egui_diagnostic_policy(&self, outcome: &mut ScriptEvalOutcome);

        /// Maximum number of rounds this suite can run.
        pub fn round_limit(&self) -> u32;
    }

    /// Result of running a full suite.
    #[derive(Clone, Debug, PartialEq)]
    pub struct SuiteResult {
        /// Per-script results in execution order.
        pub results: Vec<ScriptResult>,
        /// Per-round timings.
        pub rounds: Vec<SuiteRoundResult>,
        /// Maximum number of rounds requested for this suite invocation.
        pub requested_rounds: u32,
        /// Total suite runtime in milliseconds.
        pub elapsed_ms: u64,
    }

    impl SuiteResult {
        /// Count failing scripts.
        pub fn failed(&self) -> usize;

        /// Count passing scripts.
        pub fn passed(&self) -> usize;

        /// Render suite results as printable lines.
        pub fn render_lines(&self, verbose: bool) -> Vec<String>;

        /// Count skipped scripts.
        pub fn skipped(&self) -> usize;

        /// Returns `true` when every discovered script passed.
        pub fn success(&self) -> bool;
    }

    /// Runtime summary for one repeated suite round.
    #[derive(Clone, Debug, Eq, PartialEq)]
    pub struct SuiteRoundResult {
        /// One-based round index.
        pub round: u32,
        /// Round runtime in milliseconds.
        pub elapsed_ms: u64,
    }

    /// Repetition behavior for one smoke suite invocation.
    #[derive(Clone, Copy, Debug, Eq, PartialEq)]
    pub enum SuiteRunMode {
        /// Run the selected scripts this many times. Values below 1 are treated as
        /// one round.
        Repeat(u32),
        /// Repeat until the first failure, stopping after at most this many rounds.
        /// Values below 1 are treated as one round.
        UntilFail(u32),
    }

    impl SuiteRunMode {
        /// Run the selected scripts once.
        pub const ONCE: Self = _;
        /// Return the maximum number of rounds this mode can run.
        pub fn round_limit(self) -> u32;
    }

    /// Discovered smoke script metadata for list mode.
    #[derive(Clone, Debug, Eq, PartialEq, Serialize)]
    pub struct SuiteScriptInfo {
        /// Forward-slash-normalized display path.
        pub path: String,
        /// Script file size in bytes.
        pub size: u64,
    }

    /// Discover the selected smoke scripts without running them.
    pub fn discover_suite_scripts(config: &SuiteConfig) -> std::io::Result<Vec<SuiteScriptInfo>>;

    /// Run a smoketest suite against a live `DevMcp` instance.
    ///
    /// Blocks the calling thread on `handle` for each script. Prefer
    /// [`run_suite_with`] when the caller already owns the async context.
    pub fn run_suite(devmcp: &DevMcp, handle: &Handle, config: &SuiteConfig) -> SuiteResult;

    /// Run a smoketest suite through a caller-supplied script executor.
    pub fn run_suite_with<F>(config: &SuiteConfig, execute: F) -> SuiteResult
    where
        F: FnMut(ScriptRunRequest) -> Result<ScriptEvalOutcome, String>;
}
