// @generated by `ruskel-snapshot`; do not edit.
//
// Package: eguidev
// Publish: crates.io
// Workspace dependencies: none
// Workspace dependents: edev, eguidev_demo, eguidev_runtime
// Unnameable: crate::diagnostics::DiagnosticReceiver, crate::fixtures::FixtureManager, crate::fixtures::UiFixtureReceiver, crate::types::DataCondition, crate::types::ScrollAtCondition, crate::viewports::CaptureSnapshot

//! Cross-target instrumentation for AI-assisted egui development.
//!
//! `eguidev` captures widget state at frame boundaries and injects input
//! through an egui plugin registered on the first instrumented frame, keeping
//! automation aligned with the app's real event loop. This crate is the
//! instrumentation half of the automation stack: it is valid for native and
//! `wasm32` builds, and it intentionally does not ship the embedded script
//! runtime, MCP server, or screenshot machinery.
//!
//! # Quick start
//!
//! Add a [`DevMcp`] handle to your app state and wrap each frame with
//! [`FrameGuard`]. Input injection is automatic from there: the first
//! [`FrameGuard`] registers an egui plugin that drains queued input into
//! every pass of every viewport, so apps do not need any raw-input wiring.
//! The handle stays inert until a native app opts into `eguidev_runtime` and
//! attaches the embedded runtime in one bootstrap location.
//!
//! ```rust,ignore
//! use eframe::{App, egui};
//! use eguidev::{DevMcp, DevUiExt};
//!
//! struct MyApp {
//!     devmcp: DevMcp,
//!     name: String,
//! }
//!
//! impl App for MyApp {
//!     fn ui(&mut self, ui: &mut egui::Ui, _frame: &mut eframe::Frame) {
//!         eguidev::frame_scope(&self.devmcp, ui, "root", |ui| {
//!             ui.dev_text_edit("app.name", &mut self.name);
//!             if ui.dev_button("app.submit", "Submit").clicked() {
//!                 // ...
//!             }
//!         });
//!     }
//! }
//! ```
//!
//! # Build modes
//!
//! - **Cross-target instrumentation**: depend on `eguidev` only. [`DevMcp`],
//!   [`FrameGuard`], widget tagging, and fixtures all compile for native and
//!   `wasm32` targets.
//! - **Native embedded runtime**: add an app-local feature that enables the
//!   optional `eguidev_runtime` dependency, then call
//!   `eguidev_runtime::attach(devmcp)` in one bootstrap location. Keep that
//!   branch local to startup code instead of pushing `#[cfg]` into widget code.
//!
//! # Instrumenting widgets
//!
//! Use the [`DevUiExt`] trait for standard widgets. Each `dev_*` method takes
//! an explicit string id and auto-populates role, label, and value metadata:
//!
//! ```rust,ignore
//! if ui.dev_button("settings.save", "Save").clicked() {
//!     save_settings();
//! }
//! ui.dev_text_edit("settings.name", &mut name);
//! ui.dev_checkbox("settings.enabled", &mut enabled, "Enabled");
//! ui.dev_slider("settings.level", &mut level, 0.0..=100.0);
//! ```
//!
//! Custom widgets have their own recording primitives. Pick by what you hold:
//!
//! | You hold                                    | Use                        |
//! | ------------------------------------------- | -------------------------- |
//! | a closure that draws and returns a response  | [`track_widget`]           |
//! | the same, and a role to declare              | [`track_widget_with_meta`] |
//! | an `egui::Response` already                  | [`track_response`]         |
//! | a painter-drawn rect                         | [`publish_rect_meta`]      |
//! | a painter-drawn rect with children           | [`publish_rect_container`] |
//! | a scope whose widget is recorded elsewhere   | [`begin_container`]        |
//! | a scope and its widget together              | [`container`]              |
//!
//! `track_*` records something that has an `egui::Response`, so enabled,
//! focused, and visible state come from egui. `publish_rect_*` publishes
//! painter-drawn geometry, which has no response, so [`WidgetMeta`] states that
//! metadata instead.
//!
//! Set [`WidgetMeta::visible`] on every widget you record by hand. It defaults
//! to `false`, and an invisible widget is hidden from the default lookups.
//!
//! Custom widgets that should accept scripted `set_value(...)` calls must also
//! consume queued overrides before rendering:
//!
//! ```rust,ignore
//! let id = "settings.mode";
//! if let Some(crate::WidgetValue::Int(index)) = take_widget_value_override(ui, id) {
//!     *selected = index as usize;
//! }
//!
//! let response = render_custom_mode_picker(ui, selected);
//! track_response(
//!     id,
//!     &response,
//!     WidgetMeta {
//!         role: WidgetRoleMeta::ComboBox {
//!             options: mode_labels.clone(),
//!         },
//!         value: Some(WidgetValue::Int(*selected as i64)),
//!         visible: ui.is_visible() && ui.is_rect_visible(response.rect),
//!         ..Default::default()
//!     },
//! );
//! ```
//!
//! Only the variant the script sends is consumed. A `set_value` whose type does
//! not match the pattern above is dropped, so match the variant your role
//! publishes.
//!
//! [`WidgetRoleMeta`] carries the metadata that each role requires, so a
//! recorded scroll area always has a content size and a recorded slider always
//! has a range. Use [`WidgetRoleMeta::Plain`] only for roles with no metadata,
//! such as a label or a separator.
//!
//! Painter-drawn output has no `egui::Response`. Publish a rect with
//! [`publish_rect_meta`], and publish a painter-drawn hierarchy with
//! [`publish_rect_container`] so the children nest under their canvas instead
//! of overlapping it.
//!
//! Widget ids are the one canonical selector in the scripting API. Explicit ids
//! must be unique within a captured frame; duplicates are treated as a hard
//! automation fault.
//!
//! # Fixtures
//!
//! Apps register fixtures with [`DevMcp::fixtures`] and exactly one handler:
//! [`DevMcp::on_fixture_runtime`] for automation-thread setup or
//! [`DevMcp::on_fixture_ui`] for setup that must run on the egui UI thread.
//! Registering a second handler, of either kind, is a configuration error.
//! A handler reaches app state by closing over it, usually an
//! `Arc<Mutex<AppState>>` shared with the app's render code.
//! A fixture without preconditions is an independently invokable baseline. A
//! fixture with preconditions is a transition that callers invoke only after
//! establishing its declared entry state. Both kinds leave the app in a state
//! described by ready conditions. Use typed fixture params for controlled
//! variants and handler-returned values or ready for dynamic fixture outcomes.
//! Scripts call `eguidev.fixture("name", params?)` to apply the named fixture,
//! wait for a fresh capture, verify static and returned ready conditions, and
//! receive the returned values. Widget and viewport references resolve fresh
//! across fixture boundaries. Pass `{ wait = false }` only when a script
//! intentionally needs the state before ready conditions are satisfied.
//!
//! # Scripting reference
//!
//! The canonical Luau API, direct script evaluation helpers, and the smoketest
//! runner all live in `eguidev_runtime`. The app serves the checked-in
//! definitions through `script_api`; `edev docs` prints the same bytes.

use std::{
    any::Any,
    collections::{BTreeMap, HashSet},
    error::Error,
    fmt::{Debug, Display},
    ops::RangeInclusive,
    sync::{Arc, Mutex, MutexGuard, atomic::AtomicU64},
    time::{Duration, Instant},
};

use egui::{
    Color32, Context, CursorIcon, Event, Galley, ImageSource, InnerResponse, Key, RawInput,
    Response, ScrollArea, Ui, ViewportCommand, ViewportId, WidgetText,
    containers::collapsing_header::CollapsingResponse, data::output::FullOutput,
    scroll_area::ScrollAreaOutput,
};
use schemars::JsonSchema;
use serde::Serialize;
use serde_core::de::Deserialize;
use serde_json::Value;

/// Helper extensions for recording scroll areas with explicit ids.
// Not dyn-compatible.
pub trait DevScrollAreaExt {
    /// Show a scroll area and record it with DevMCP metadata.
    fn dev_show<R>(
        self,
        ui: &mut Ui,
        id: impl Into<String>,
        add_contents: impl FnOnce(&mut Ui) -> R,
    ) -> ScrollAreaOutput<R>;

    /// Show a scroll area with viewport access and record it with DevMCP
    /// metadata.
    fn dev_show_viewport<R>(
        self,
        ui: &mut Ui,
        id: impl Into<String>,
        add_contents: impl FnOnce(&mut Ui, egui::Rect) -> R,
    ) -> ScrollAreaOutput<R>;
}

impl DevScrollAreaExt for ScrollArea {}

/// Helper extensions for recording common widgets with explicit ids.
///
/// Prefer these for standard widgets; they auto-populate role/type/value/label
/// metadata.
// Not dyn-compatible.
pub trait DevUiExt {
    /// Add a button with an explicit id.
    #[must_use = "a button does nothing unless its response is handled"]
    fn dev_button(&mut self, id: impl Into<String>, text: impl Into<WidgetText>) -> Response;

    /// Add a selected-aware button with explicit metadata.
    #[must_use = "a button does nothing unless its response is handled"]
    fn dev_button_with(
        &mut self,
        id: impl Into<String>,
        text: impl Into<WidgetText>,
        options: ButtonOptions,
    ) -> Response;

    /// Add a checkbox with an explicit id.
    fn dev_checkbox(
        &mut self,
        id: impl Into<String>,
        value: &mut bool,
        text: impl Into<WidgetText>,
    ) -> Response;

    /// Add an indeterminate-aware checkbox with explicit metadata.
    fn dev_checkbox_with(
        &mut self,
        id: impl Into<String>,
        value: &mut bool,
        text: impl Into<WidgetText>,
        options: CheckboxOptions,
    ) -> Response;

    /// Add a collapsing header with an explicit id, bound to app state.
    ///
    /// Records a `{id}.body` container for the expanded contents.
    fn dev_collapsing<R>(
        &mut self,
        id: impl Into<String>,
        open: &mut bool,
        heading: impl Into<WidgetText>,
        add_contents: impl FnOnce(&mut Ui) -> R,
    ) -> CollapsingResponse<R>;

    /// Add a color-edit button with an explicit id.
    fn dev_color_edit(&mut self, id: impl Into<String>, color: &mut Color32) -> Response;

    /// Add a combo box with an explicit id.
    fn dev_combo_box<T: ToString>(
        &mut self,
        id: impl Into<String>,
        label: impl Into<String>,
        selected: &mut usize,
        options: &[T],
    ) -> Response;

    /// Add a float drag value with an explicit id.
    fn dev_drag_value(&mut self, id: impl Into<String>, value: &mut f32) -> Response;

    /// Add an integer drag value with an explicit id.
    fn dev_drag_value_i32(&mut self, id: impl Into<String>, value: &mut i32) -> Response;

    /// Add an integer drag value with an explicit constrained range.
    fn dev_drag_value_i32_range(
        &mut self,
        id: impl Into<String>,
        value: &mut i32,
        range: RangeInclusive<i32>,
    ) -> Response;

    /// Add a float drag value with an explicit constrained range.
    fn dev_drag_value_range(
        &mut self,
        id: impl Into<String>,
        value: &mut f32,
        range: RangeInclusive<f32>,
    ) -> Response;

    /// Add a hyperlink with an explicit id, using its URL as label and value
    /// metadata.
    fn dev_hyperlink(&mut self, id: impl Into<String>, url: impl ToString) -> Response;

    /// Add a hyperlink with an explicit id, label, and URL metadata.
    fn dev_hyperlink_to(
        &mut self,
        id: impl Into<String>,
        label: impl Into<WidgetText>,
        url: impl ToString,
    ) -> Response;

    /// Add an image with an explicit id and developer-provided description.
    fn dev_image<'a>(
        &mut self,
        id: impl Into<String>,
        description: impl Into<String>,
        source: impl Into<ImageSource<'a>>,
    ) -> Response;

    /// Add a label with an explicit id.
    fn dev_label(&mut self, id: impl Into<String>, text: impl Into<WidgetText>) -> Response;

    /// Add a link with an explicit id.
    fn dev_link(&mut self, id: impl Into<String>, text: impl Into<WidgetText>) -> Response;

    /// Add a menu button with an explicit id.
    ///
    /// Records a `{id}.menu` container for the menu contents.
    fn dev_menu_button<R>(
        &mut self,
        id: impl Into<String>,
        text: impl Into<WidgetText>,
        add_contents: impl FnOnce(&mut Ui) -> R,
    ) -> InnerResponse<Option<R>>;

    /// Add a progress bar with an explicit id.
    fn dev_progress_bar(&mut self, id: impl Into<String>, progress: f32) -> Response;

    /// Add a progress bar with explicit overlay text options.
    fn dev_progress_bar_with(
        &mut self,
        id: impl Into<String>,
        progress: f32,
        options: ProgressBarOptions,
    ) -> Response;

    /// Add a radio value with an explicit id.
    fn dev_radio_value<V: Clone + PartialEq>(
        &mut self,
        id: impl Into<String>,
        current: &mut V,
        alternative: V,
        text: impl Into<WidgetText>,
    ) -> Response;

    /// Add a selectable value with an explicit id.
    fn dev_selectable_value<V: Clone + PartialEq>(
        &mut self,
        id: impl Into<String>,
        current: &mut V,
        alternative: V,
        text: impl Into<WidgetText>,
    ) -> Response;

    /// Add a separator with an explicit id.
    fn dev_separator(&mut self, id: impl Into<String>) -> Response;

    /// Add a slider with an explicit id.
    fn dev_slider(
        &mut self,
        id: impl Into<String>,
        value: &mut f32,
        range: RangeInclusive<f32>,
    ) -> Response;

    /// Add a spinner with an explicit id.
    fn dev_spinner(&mut self, id: impl Into<String>) -> Response;

    /// Add a text edit with an explicit id.
    fn dev_text_edit(&mut self, id: impl Into<String>, text: &mut String) -> Response;

    /// Add a multiline text edit with an explicit id.
    fn dev_text_edit_multiline(&mut self, id: impl Into<String>, text: &mut String) -> Response;

    /// Add a text edit with explicit mode metadata.
    ///
    /// `options.password` masks the field in the UI only. The recorded value
    /// stays cleartext for scripts, dumps, and failure bundles.
    fn dev_text_edit_with(
        &mut self,
        id: impl Into<String>,
        text: &mut String,
        options: TextEditOptions,
    ) -> Response;

    /// Add a toggle value with an explicit id.
    fn dev_toggle_value(
        &mut self,
        id: impl Into<String>,
        selected: &mut bool,
        text: impl Into<WidgetText>,
    ) -> Response;
}

impl DevUiExt for Ui {}

/// Controls shared by high-level actions.
#[derive(Clone, Copy, Debug, Default, Deserialize<'de>, Eq, PartialEq, Serialize)]
pub struct ActionOptions {
    /// Wait controls used before and after the action.
    #[serde(flatten)]
    pub wait: WaitOptions,
    /// Whether to wait for deterministic settlement after queuing the action.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub settle: Option<bool>,
}

impl JsonSchema for ActionOptions {}

#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct AutomationOptions {
    pub keep_alive: bool,
    pub animations: bool,
}

/// Options for selected-aware buttons.
#[derive(Clone, Copy, Debug, Default)]
pub struct ButtonOptions {
    /// Whether the button is in a selected/toggled state.
    pub selected: bool,
}

/// Options for third-state checkboxes.
#[derive(Clone, Copy, Debug, Default)]
pub struct CheckboxOptions {
    /// Whether the checkbox should render as indeterminate.
    pub indeterminate: bool,
}

/// RAII guard that pops a container scope when dropped.
pub struct ContainerGuard {/* private fields */}

impl Drop for ContainerGuard {}

/// DevMCP handle stored in app state.
///
/// `Clone` is a cheap shared handle: configuration, the shutdown handler,
/// fixtures, diagnostics, and idle providers are observed by every clone.
#[derive(Clone, Debug, Default)]
pub struct DevMcp {/* private fields */}

impl DevMcp {
    #[doc(hidden)]
    pub fn activate_runtime(self, inner: Arc<Inner>, hooks: Arc<dyn RuntimeHooks>) -> Self;

    /// Enable or disable egui animations while automation is attached.
    pub fn animations(self, animations: bool) -> Self;

    /// Configure runtime-owned automation behavior.
    pub fn automation_options(self, options: AutomationOptions) -> Self;

    /// Clear script-visible widgets for a viewport that the app has hidden.
    pub fn clear_viewport(&self, viewport_id: ViewportId);

    /// Register a named diagnostic provider that runs on the automation runtime
    /// thread.
    pub fn diagnostic<F>(
        self,
        name: impl Into<String>,
        provider: F,
    ) -> Result<Self, DevMcpConfigError>
    where
        F: 'static + Fn() -> DiagnosticResult + Send + Sync;

    /// Register a named diagnostic provider that runs on the UI thread.
    pub fn diagnostic_ui<F>(
        self,
        name: impl Into<String>,
        provider: F,
    ) -> Result<Self, DevMcpConfigError>
    where
        F: 'static + FnMut(&Context) -> DiagnosticResult + Send;

    /// Register fixture metadata for discovery and validation.
    pub fn fixtures(self, fixtures: impl IntoIterator<Item = FixtureSpec>) -> Self;

    #[doc(hidden)]
    pub fn inner_arc(&self) -> Option<Arc<Inner>>;

    /// Returns true if DevMCP automation is attached.
    pub fn is_enabled(&self) -> bool;

    /// Enable or disable runtime repaint keep-alive while automation is
    /// attached.
    pub fn keep_alive(self, keep_alive: bool) -> Self;

    /// Create a new inert DevMCP handle.
    pub fn new() -> Self;

    /// Register the fixture handler, to run on the automation thread.
    ///
    /// An app registers exactly one fixture handler. Calling this after either
    /// handler is already registered returns a `duplicate_fixture_handler`
    /// configuration error. The handler reaches app state by closing over it.
    pub fn on_fixture_runtime<F>(self, handler: F) -> Result<Self, DevMcpConfigError>
    where
        F: 'static + Fn(&FixtureCall) -> FixtureResult + Send + Sync;

    /// Register the fixture handler, to run on the egui UI thread.
    ///
    /// Use this when setup must touch the `egui::Context`. An app registers
    /// exactly one fixture handler. Calling this after either handler is
    /// already registered returns a `duplicate_fixture_handler` configuration
    /// error. The handler reaches app state by closing over it.
    pub fn on_fixture_ui<F>(self, handler: F) -> Result<Self, DevMcpConfigError>
    where
        F: 'static + FnMut(&Context, &FixtureCall) -> FixtureResult + Send;

    /// Register an app-level idle check that runs on the automation runtime
    /// thread.
    pub fn on_idle<F>(self, is_idle: F) -> Result<Self, DevMcpConfigError>
    where
        F: 'static + Fn() -> bool + Send + Sync;

    /// Register an app-level idle check that runs on the UI thread at root
    /// frame end.
    pub fn on_idle_ui<F>(self, is_idle: F) -> Result<Self, DevMcpConfigError>
    where
        F: 'static + FnMut(&Context) -> bool + Send;

    /// Register a nonblocking application shutdown request.
    ///
    /// Edev calls this handler on the app MCP runtime thread during managed
    /// shutdown. The handler must publish its request to the application's
    /// lifecycle owner and return immediately. If no handler is registered,
    /// Eguidev closes the root viewport.
    pub fn on_shutdown<F>(self, handler: F) -> Self
    where
        F: 'static + Fn() + Send + Sync;

    #[doc(hidden)]
    pub fn runtime_hooks(&self) -> Option<Arc<dyn RuntimeHooks>>;

    /// Enable or disable verbose internal logging for DevMCP operations.
    pub fn verbose_logging(self, verbose_logging: bool) -> Self;
}

/// Configuration error returned while building a [`crate::DevMcp`] handle.
///
/// Every code names a registration the handle refuses:
///
/// - `duplicate_fixture_handler`: a fixture handler is already registered. An
///   app registers exactly one, from either `on_fixture_ui` or
///   `on_fixture_runtime`.
/// - `duplicate_idle_provider`: an idle provider is already registered.
/// - `duplicate_diagnostic`: that diagnostic name is already registered.
/// - `empty_diagnostic_name`: the diagnostic name was blank.
#[derive(Clone, Debug, Deserialize<'de>, Display, Error, PartialEq, Serialize)]
#[error("{message}")]
pub struct DevMcpConfigError {
    /// Stable machine-readable error code.
    pub code: String,
    /// Human-readable error message.
    pub message: String,
    /// Optional machine-readable error details.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub details: Option<Value>,
}

/// Structured failure returned by an app diagnostic provider.
///
/// An app chooses its own `code` values. `eguidev` produces these itself when
/// it cannot reach a provider:
///
/// - `timeout`: a UI-thread provider did not answer before the deadline.
/// - `panic`: the provider panicked, and `message` carries the payload.
/// - `internal`: the provider was dropped without returning a result.
/// - `pending_ui`: the provider needs a UI frame that has not run yet.
#[derive(Clone, Debug, Deserialize<'de>, PartialEq, Serialize)]
pub struct DiagnosticError {
    /// Stable machine-readable error code.
    pub code: String,
    /// Human-readable error message.
    pub message: String,
    /// Optional machine-readable error details.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub details: Option<Value>,
}

impl DiagnosticError {
    /// Create a diagnostic error.
    pub fn new(code: impl Into<String>, message: impl Into<String>) -> Self;

    /// Attach structured error details.
    pub fn with_details(self, details: Value) -> Self;
}

/// Result returned by an app diagnostic provider.
pub type DiagnosticResult = Result<Value, DiagnosticError>;

/// Options for a drag action.
#[derive(Clone, Copy, Debug, Default, Deserialize<'de>, PartialEq, Serialize)]
pub struct DragOptions {
    /// Shared action controls.
    #[serde(flatten)]
    pub action: ActionOptions,
    /// Optional normalized starting position within the source widget.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub from: Option<Vec2>,
}

impl JsonSchema for DragOptions {}

/// Fixture call passed to a registered handler.
#[derive(Clone, Debug, Deserialize<'de>, PartialEq, Serialize)]
pub struct FixtureCall {
    /// Fixture name.
    pub name: String,
    /// Validated params with defaults filled in.
    pub params: FixtureParams,
}

impl JsonSchema for FixtureCall {}

/// Structured fixture handler failure.
///
/// A handler chooses its own `code` values, such as `unknown_fixture`.
/// `eguidev` produces these itself before or around the handler:
///
/// - `no_handler`: the app registered no fixture handler.
/// - `unknown_param`, `missing_param`, `invalid_param_type`,
///   `invalid_param_choice`, `param_below_min`, `param_above_max`: the call did
///   not satisfy the fixture's declared params, and `details` names the param.
/// - `timeout`: a UI-thread handler did not run before the deadline.
/// - `panic`: the handler panicked, and `message` carries the payload.
/// - `internal`: the handler was dropped without returning a result.
#[derive(Clone, Debug, Deserialize<'de>, PartialEq, Serialize)]
pub struct FixtureError {
    /// Stable machine-readable error code.
    pub code: String,
    /// Human-readable error message.
    pub message: String,
    /// Optional machine-readable error details.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub details: Option<Value>,
}

impl FixtureError {
    /// Attach structured error details.
    pub fn details<T: Serialize>(self, details: T) -> Self;

    /// Create a fixture error.
    pub fn new(code: impl Into<String>, message: impl Into<String>) -> Self;
}

impl JsonSchema for FixtureError {}

/// One typed fixture parameter in a fixture catalog entry.
#[derive(Clone, Debug, Deserialize<'de>, Serialize)]
pub struct FixtureParam {
    /// Parameter name.
    pub name: String,
    /// Parameter scalar kind.
    pub kind: ParamKind,
    /// Human-readable parameter description.
    pub description: String,
    /// Optional default. Missing default means the caller must supply the
    /// param.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub default: Option<WidgetValue>,
    /// Optional exact allowed values.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub choices: Vec<WidgetValue>,
    /// Optional inclusive minimum for int/float params.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub min: Option<f64>,
    /// Optional inclusive maximum for int/float params.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max: Option<f64>,
}

impl FixtureParam {
    /// Create a boolean fixture parameter.
    pub fn bool(name: impl Into<String>, description: impl Into<String>) -> Self;

    /// Restrict this parameter to exact choices.
    pub fn choices<I, V>(self, values: I) -> Self
    where
        I: IntoIterator<Item = V>,
        V: Into<WidgetValue>;

    /// Set this parameter's default value.
    pub fn default(self, value: impl Into<WidgetValue>) -> Self;

    /// Create a floating-point fixture parameter.
    pub fn float(name: impl Into<String>, description: impl Into<String>) -> Self;

    /// Create an integer fixture parameter.
    pub fn int(name: impl Into<String>, description: impl Into<String>) -> Self;

    /// Set an inclusive numeric range.
    pub fn range(self, min: f64, max: f64) -> Self;

    /// Create a text fixture parameter.
    pub fn text(name: impl Into<String>, description: impl Into<String>) -> Self;
}

impl JsonSchema for FixtureParam {}

/// Validated fixture params passed to a handler.
#[derive(Clone, Debug, Default, Deserialize<'de>, PartialEq, Serialize)]
pub struct FixtureParams(_);

impl FixtureParams {
    /// Return the validated params as a map.
    pub fn as_map(&self) -> &BTreeMap<String, WidgetValue>;

    /// Get a bool param by name.
    pub fn bool(&self, name: &str) -> bool;

    /// Get a float param by name.
    pub fn float(&self, name: &str) -> f64;

    /// Get a param by name.
    pub fn get(&self, name: &str) -> Option<&WidgetValue>;

    /// Get an int param by name.
    pub fn int(&self, name: &str) -> i64;

    /// Consume this wrapper into the validated param map.
    pub fn into_map(self) -> BTreeMap<String, WidgetValue>;

    /// Get a text param by name.
    pub fn text(&self, name: &str) -> &str;
}

impl JsonSchema for FixtureParams {}

/// Successful fixture handler response.
#[derive(Clone, Debug, Default, Deserialize<'de>, PartialEq, Serialize)]
pub struct FixtureResponse {
    /// Handler-returned values exposed to scripts and CLI output.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub values: BTreeMap<String, WidgetValue>,
    /// Handler-returned dynamic ready waited on together with the spec ready.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub ready: Vec<FixtureTargetSpec>,
}

impl FixtureResponse {
    /// Create an empty fixture response.
    pub fn new() -> Self;

    /// Add a handler-returned dynamic ready.
    pub fn ready(self, ready: FixtureTargetSpec) -> Self;

    /// Add a handler-returned value.
    pub fn value(self, name: impl Into<String>, value: impl Into<WidgetValue>) -> Self;
}

impl JsonSchema for FixtureResponse {}

/// Result returned by a fixture handler.
pub type FixtureResult = Result<FixtureResponse, FixtureError>;

/// Fixture metadata advertised by an app.
#[derive(Clone, Debug, Deserialize<'de>, Serialize)]
pub struct FixtureSpec {
    /// Fixture name.
    pub name: String,
    /// Fixture description.
    pub description: String,
    /// Declarative conditions that must be satisfied before fixture
    /// application.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub preconditions: Vec<FixtureTargetSpec>,
    /// Declarative ready conditions for the fixture baseline.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub ready: Vec<FixtureTargetSpec>,
    /// Typed scalar params accepted by this fixture.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub params: Vec<FixtureParam>,
    /// Searchable fixture categories used by docs and CLI output.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tags: Vec<String>,
}

impl FixtureSpec {
    /// Return a human-readable summary of the readiness contract.
    pub fn describe_readiness(&self) -> String;

    /// Return whether this fixture is a transition with entry requirements.
    pub fn is_transition(&self) -> bool;

    /// Create a new fixture specification.
    pub fn new(name: impl Into<String>, description: impl Into<String>) -> Self;

    /// Add a typed fixture parameter.
    pub fn param(self, param: FixtureParam) -> Self;

    /// Add a visible-widget precondition checked before fixture application.
    pub fn precondition(self, widget_id: impl Into<String>) -> Self;

    /// Add a visible-widget precondition scoped to a viewport.
    pub fn precondition_in(
        self,
        widget_id: impl Into<String>,
        viewport: impl Into<ViewportSel>,
    ) -> Self;

    /// Add an exact-value precondition checked before fixture application.
    pub fn precondition_value(self, widget_id: impl Into<String>, value: WidgetValue) -> Self;

    /// Add an exact-value precondition scoped to a viewport.
    pub fn precondition_value_in(
        self,
        widget_id: impl Into<String>,
        value: WidgetValue,
        viewport: impl Into<ViewportSel>,
    ) -> Self;

    /// Add a visible-widget ready condition.
    pub fn ready(self, widget_id: impl Into<String>) -> Self;

    /// Add a widget-data ready condition.
    pub fn ready_data(
        self,
        widget_id: impl Into<String>,
        pointer: impl Into<String>,
        equals: impl Into<Value>,
    ) -> Self;

    /// Add a widget-data ready condition scoped to a viewport.
    pub fn ready_data_in(
        self,
        widget_id: impl Into<String>,
        pointer: impl Into<String>,
        equals: impl Into<Value>,
        viewport: impl Into<ViewportSel>,
    ) -> Self;

    /// Add a visible-widget ready condition scoped to a viewport.
    pub fn ready_in(self, widget_id: impl Into<String>, viewport: impl Into<ViewportSel>) -> Self;

    /// Add an exact-label ready condition.
    pub fn ready_label(self, widget_id: impl Into<String>, text: impl Into<String>) -> Self;

    /// Add an exact-label ready condition scoped to a viewport.
    pub fn ready_label_in(
        self,
        widget_id: impl Into<String>,
        text: impl Into<String>,
        viewport: impl Into<ViewportSel>,
    ) -> Self;

    /// Add a scroll-readiness condition.
    pub fn ready_scroll(self, widget_id: impl Into<String>) -> Self;

    /// Add a scroll-position ready condition.
    pub fn ready_scroll_at(
        self,
        widget_id: impl Into<String>,
        offset: impl Into<Vec2>,
        tolerance: f32,
    ) -> Self;

    /// Add a scroll-position ready condition scoped to a viewport.
    pub fn ready_scroll_at_in(
        self,
        widget_id: impl Into<String>,
        offset: impl Into<Vec2>,
        tolerance: f32,
        viewport: impl Into<ViewportSel>,
    ) -> Self;

    /// Add a scroll-readiness condition scoped to a viewport.
    pub fn ready_scroll_in(
        self,
        widget_id: impl Into<String>,
        viewport: impl Into<ViewportSel>,
    ) -> Self;

    /// Add an exact-value ready condition.
    pub fn ready_value(self, widget_id: impl Into<String>, value: WidgetValue) -> Self;

    /// Add an exact-value ready condition scoped to a viewport.
    pub fn ready_value_in(
        self,
        widget_id: impl Into<String>,
        value: WidgetValue,
        viewport: impl Into<ViewportSel>,
    ) -> Self;

    /// Add a fixture tag used by CLI/docs output.
    pub fn tag(self, tag: impl Into<String>) -> Self;

    /// Validate fixture metadata and readiness conditions.
    pub fn validate(&self, require_ready: bool) -> Result<(), String>;

    /// Validate and normalize a caller-supplied param map.
    pub fn validate_params(
        &self,
        supplied: BTreeMap<String, WidgetValue>,
    ) -> Result<FixtureParams, FixtureError>;
}

impl JsonSchema for FixtureSpec {}

/// One widget target and condition in a fixture readiness contract.
#[derive(Clone, Debug, Deserialize<'de>, PartialEq, Serialize)]
pub struct FixtureTargetSpec {
    /// Widget id to resolve from the registry.
    pub widget_id: String,
    /// Optional viewport selector (`root`, semantic name, or `vp:...`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub viewport_id: Option<String>,
    /// Readiness condition to evaluate against the widget state.
    pub condition: WidgetCondition,
}

impl FixtureTargetSpec {
    /// Create a widget-data ready.
    pub fn data(
        widget_id: impl Into<String>,
        pointer: impl Into<String>,
        equals: impl Into<Value>,
    ) -> Self;

    /// Return a human-readable description of the ready.
    pub fn describe(&self) -> String;

    /// Scope this ready to a viewport selector.
    pub fn in_viewport(self, viewport: impl Into<ViewportSel>) -> Self;

    /// Create an exact-label ready.
    pub fn label(widget_id: impl Into<String>, label: impl Into<String>) -> Self;

    /// Create a fixture target with an explicit shared condition.
    pub fn new(widget_id: impl Into<String>, condition: WidgetCondition) -> Self;

    /// Create a scroll-position ready.
    pub fn scroll_at(widget_id: impl Into<String>, offset: impl Into<Vec2>, tolerance: f32)
    -> Self;

    /// Create a scroll-readiness target.
    pub fn scroll_ready(widget_id: impl Into<String>) -> Self;

    /// Validate the ready contents.
    pub fn validate(&self) -> Result<(), String>;

    /// Create an exact-value ready.
    pub fn value(widget_id: impl Into<String>, value: impl Into<WidgetValue>) -> Self;

    /// Create a visible-widget readiness target.
    pub fn visible(widget_id: impl Into<String>) -> Self;
}

impl JsonSchema for FixtureTargetSpec {}

/// RAII guard that calls `begin_frame` and `end_frame` automatically.
#[must_use = "FrameGuard must be held for the duration of the frame"]
pub struct FrameGuard<'a> {/* private fields */}

impl<'a> FrameGuard<'a> {
    /// Create a new frame guard for the provided DevMcp.
    pub fn new(devmcp: &'a DevMcp, ctx: &'a Context) -> Self;
}

impl Drop for FrameGuard<'_> {}

/// Supported scalar kinds for fixture parameters.
#[derive(Clone, Copy, Debug, Deserialize<'de>, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum ParamKind {
    /// Boolean fixture parameter.
    Bool,
    /// Signed integer fixture parameter.
    Int,
    /// Floating-point fixture parameter.
    Float,
    /// String fixture parameter.
    Text,
}

impl JsonSchema for ParamKind {}

/// Pointer button used by clicks and raw pointer events.
#[derive(Clone, Copy, Debug, Deserialize<'de>, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum PointerButton {
    /// Primary pointer button.
    Primary,
    /// Secondary pointer button.
    Secondary,
    /// Middle pointer button.
    Middle,
}

impl JsonSchema for PointerButton {}

/// A logical point in egui coordinates.
#[derive(Clone, Copy, Debug, Deserialize<'de>, PartialEq, Serialize)]
pub struct Pos2 {
    /// X coordinate in points.
    pub x: f32,
    /// Y coordinate in points.
    pub y: f32,
}

impl From<Pos2> for egui::Pos2 {}

impl From<egui::Pos2> for Pos2 {}

impl JsonSchema for Pos2 {}

/// Options for progress bars.
#[derive(Clone, Debug, Default)]
pub struct ProgressBarOptions {
    /// Optional overlay text rendered inside the bar.
    pub text: Option<String>,
    /// Whether to show a percentage when `text` is absent.
    pub show_percentage: bool,
}

/// Press or release action used by raw input events.
#[derive(Clone, Copy, Debug, Deserialize<'de>, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum RawInputAction {
    /// Press the key or pointer button.
    Press,
    /// Release the key or pointer button.
    Release,
}

impl JsonSchema for RawInputAction {}

/// One raw input event. Raw input queues exactly one event and does not settle.
#[derive(Clone, Debug, Deserialize<'de>, Serialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum RawInputEvent {
    /// Move the pointer to an absolute egui position.
    PointerMove {
        /// Absolute egui position.
        position: Pos2,
    },
    /// Press or release one pointer button.
    PointerButton {
        /// Absolute egui position.
        position: Pos2,
        /// Pointer button.
        button: PointerButton,
        /// Press or release action.
        action: RawInputAction,
        /// Optional modifier state.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        modifiers: Option<Modifiers>,
    },
    /// Press or release one key.
    Key {
        /// Egui key name.
        key: String,
        /// Press or release action.
        action: RawInputAction,
        /// Optional modifier state.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        modifiers: Option<Modifiers>,
    },
    /// Insert one raw text event.
    Text {
        /// Text payload.
        text: String,
    },
    /// Insert one raw scroll event.
    Scroll {
        /// Scroll delta in egui points.
        delta: Vec2,
        /// Optional modifier state.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        modifiers: Option<Modifiers>,
    },
}

impl JsonSchema for RawInputEvent {}

/// Axis-aligned rectangle in egui coordinates.
#[derive(Clone, Copy, Debug, Deserialize<'de>, PartialEq, Serialize)]
pub struct Rect {
    /// Minimum point.
    pub min: Pos2,
    /// Maximum point.
    pub max: Pos2,
}

impl Rect {
    /// Return the center point of the rectangle in egui coordinates.
    pub fn center(self) -> Pos2;
}

impl From<Rect> for egui::Rect {}

impl From<egui::Rect> for Rect {}

impl JsonSchema for Rect {}

/// One resize command applied atomically before settlement.
#[derive(Clone, Copy, Debug, Default, Deserialize<'de>, PartialEq, Serialize)]
pub struct ResizeOptions {
    /// Shared action controls.
    #[serde(flatten)]
    pub action: ActionOptions,
    /// Requested inner viewport size.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub inner_size: Option<Vec2>,
    /// Requested minimum inner size.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub min_size: Option<Vec2>,
    /// Requested maximum inner size.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_size: Option<Vec2>,
    /// Requested resize increments.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub increments: Option<Vec2>,
    /// Whether the viewport is user-resizable.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resizable: Option<bool>,
}

impl JsonSchema for ResizeOptions {}

/// Role-specific widget metadata kept on internal registry entries.
#[derive(Clone, Debug, Deserialize<'de>, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum RoleState {
    /// Scroll area metadata.
    ScrollArea {
        /// Current scroll offset.
        offset: Vec2,
        /// Viewport size available to the scroll contents.
        viewport_size: Vec2,
        /// Total content size within the scroll area.
        content_size: Vec2,
    },
    /// Slider range metadata.
    Slider {
        /// Allowed numeric range.
        range: WidgetRange,
    },
    /// Drag value range metadata.
    DragValue {
        /// Allowed numeric range when constrained by the app.
        range: Option<WidgetRange>,
    },
    /// Combo box option labels.
    ComboBox {
        /// Available option labels.
        options: Vec<String>,
    },
    /// Selected/toggled button state.
    Button {
        /// Whether the button is in a selected state.
        selected: bool,
    },
    /// Checkbox third-state metadata.
    Checkbox {
        /// Whether the checkbox is visually indeterminate.
        indeterminate: bool,
    },
    /// Text edit configuration metadata.
    TextEdit {
        /// Whether the edit is multiline.
        multiline: bool,
        /// Whether the edit masks its input.
        password: bool,
    },
}

impl RoleState {
    /// Return checkbox indeterminate metadata when present.
    pub fn indeterminate(&self) -> Option<bool>;

    /// Return combo-box options when present.
    pub fn options(&self) -> Option<&[String]>;

    /// Project numeric range metadata into the flat scripting shape.
    pub fn range(&self) -> Option<WidgetRange>;

    /// Project scroll-area metadata into the flat scripting shape.
    pub fn scroll_state(&self) -> Option<ScrollAreaMeta>;

    /// Return button selected metadata when present.
    pub fn selected(&self) -> Option<bool>;

    /// Return text-edit metadata when present: `(multiline, password)`.
    pub fn text_edit(&self) -> Option<(bool, bool)>;
}

impl JsonSchema for RoleState {}

/// Coarse alignment used by scroll-to actions.
#[derive(Clone, Copy, Debug, Deserialize<'de>, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum ScrollAlign {
    /// Align to the top.
    Top,
    /// Align to the center.
    Center,
    /// Align to the bottom.
    Bottom,
}

impl JsonSchema for ScrollAlign {}

/// Scroll metadata captured for a scroll area.
#[derive(Clone, Copy, Debug, Deserialize<'de>, Serialize)]
pub struct ScrollAreaMeta {
    /// Current scroll offset.
    pub offset: Vec2,
    /// Viewport size available to the scroll contents.
    pub viewport_size: Vec2,
    /// Total content size within the scroll area.
    pub content_size: Vec2,
    /// Maximum reachable scroll offset after clamping.
    pub max_offset: Vec2,
}

impl ScrollAreaMeta {
    /// Build scroll metadata and derive the clamped maximum offset.
    pub fn new(offset: Vec2, viewport_size: Vec2, content_size: Vec2) -> Self;
}

impl JsonSchema for ScrollAreaMeta {}

/// Scroll area state tracker with one-shot offset jumps.
#[derive(Clone, Debug, Default)]
pub struct ScrollAreaState {/* private fields */}

impl ScrollAreaState {
    /// Request a one-shot jump to the given offset on the next frame.
    pub fn jump_to(&mut self, offset: egui::Vec2);

    /// Create a new scroll area state tracker.
    pub fn new() -> Self;

    /// The most recent scroll offset after egui applied input.
    pub fn offset(&self) -> egui::Vec2;

    /// Reset tracked state and request that the next frame jump back to the
    /// origin.
    pub fn reset(&mut self);

    /// Show a scroll area, record DevMCP metadata, and update the tracked
    /// offset.
    pub fn show<R>(
        &mut self,
        scroll_area: ScrollArea,
        ui: &mut Ui,
        id: impl Into<String>,
        add_contents: impl FnOnce(&mut Ui) -> R,
    ) -> ScrollAreaOutput<R>;

    /// Show a scroll area with viewport access, record DevMCP metadata, and
    /// update the offset.
    pub fn show_viewport<R>(
        &mut self,
        scroll_area: ScrollArea,
        ui: &mut Ui,
        id: impl Into<String>,
        add_contents: impl FnOnce(&mut Ui, egui::Rect) -> R,
    ) -> ScrollAreaOutput<R>;
}

/// Options for text-edit widgets.
#[derive(Clone, Copy, Debug, Default)]
pub struct TextEditOptions {
    /// Whether the edit is multiline.
    pub multiline: bool,
    /// Whether the edit masks its contents in the UI.
    ///
    /// Masking is presentation only. Automation still records the cleartext
    /// value in widget state, dumps, script output, and failure bundles.
    pub password: bool,
}

/// A 2D vector in egui coordinates.
#[derive(Clone, Copy, Debug, Deserialize<'de>, PartialEq, Serialize)]
pub struct Vec2 {
    /// X component in points.
    pub x: f32,
    /// Y component in points.
    pub y: f32,
}

impl From<Vec2> for egui::Vec2 {}

impl From<egui::Vec2> for Vec2 {}

impl JsonSchema for Vec2 {}

/// Shared declarative condition for viewport waits and assertions.
#[derive(Clone, Debug, Default, Deserialize<'de>, PartialEq, Serialize)]
pub struct ViewportCondition {
    /// Whether the viewport must be present or absent.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub present: Option<bool>,
    /// Required semantic viewport name.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Required exact window title.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Required window-title substring.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title_contains: Option<String>,
    /// Required focus state.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub focused: Option<bool>,
    /// Required minimized state.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub minimized: Option<bool>,
    /// Required occlusion state.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub occluded: Option<bool>,
    /// Required observed native title visibility.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub os_title_visible: Option<bool>,
    /// Required cursor icon requested by the viewport's latest frame.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor_icon: Option<String>,
    /// Required maximized state.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub maximized: Option<bool>,
    /// Required fullscreen state.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub fullscreen: Option<bool>,
    /// Minimum captured viewport frame.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub frame_at_least: Option<u64>,
}

impl ViewportCondition {
    /// Validate combinations and string conditions.
    pub fn validate(&self) -> Result<(), String>;
}

impl JsonSchema for ViewportCondition {}

/// Error returned when a semantic viewport name is reserved or invalid.
#[derive(Clone, Debug, Deserialize<'de>, Display, Eq, Error, PartialEq, Serialize)]
pub struct ViewportNameError {
    /// Stable machine-readable error code.
    pub code: String,
    /// Human-readable error message.
    pub message: String,
}

impl JsonSchema for ViewportNameError {}

/// Explicit selector for a viewport.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ViewportSel {/* private fields */}

impl ViewportSel {
    /// Select a concrete egui viewport id.
    pub fn id(id: ViewportId) -> Self;

    /// Select a semantic viewport name.
    pub fn name(name: impl Into<String>) -> Result<Self, ViewportNameError>;

    /// Parse the Luau/tool selector grammar: `root`, a semantic name, or
    /// `vp:<hex>`.
    pub fn parse(selector: impl AsRef<str>) -> Result<Self, ViewportSelParseError>;

    /// Select the root viewport.
    pub fn root() -> Self;

    /// Return the canonical string selector used in fixtures and scripts.
    pub fn to_selector_string(&self) -> String;
}

impl From<ViewportId> for ViewportSel {}

/// Error returned when parsing a viewport selector string fails.
#[derive(Clone, Debug, Deserialize<'de>, Display, Eq, Error, PartialEq, Serialize)]
pub struct ViewportSelParseError {
    /// Stable machine-readable error code.
    pub code: String,
    /// Human-readable error message.
    pub message: String,
}

impl JsonSchema for ViewportSelParseError {}

/// Timeout and polling controls shared by waits and high-level actions.
#[derive(Clone, Copy, Debug, Default, Deserialize<'de>, Eq, PartialEq, Serialize)]
pub struct WaitOptions {
    /// Optional operation timeout in milliseconds.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timeout_ms: Option<u64>,
    /// Optional interval between fresh-capture polls in milliseconds.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub poll_interval_ms: Option<u64>,
}

impl JsonSchema for WaitOptions {}

/// Shared declarative condition used by waits, assertions, actions, and
/// fixtures.
///
/// Every populated field must match. An empty condition means `present = true`.
#[derive(Clone, Debug, Default, Deserialize<'de>, Display, PartialEq, Serialize)]
pub struct WidgetCondition {
    /// Whether the widget must be present or absent.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub present: Option<bool>,
    /// Whether the widget must satisfy standard click actionability.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub actionable: Option<bool>,
    /// Required visibility state.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub visible: Option<bool>,
    /// Required coverage state: whether another egui layer covers the
    /// widget's action point.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub covered: Option<bool>,
    /// Required enabled state.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// Required keyboard-focus state.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub focused: Option<bool>,
    /// Required selection state.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub selected: Option<bool>,
    /// Required semantic widget role.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub role: Option<WidgetRole>,
    /// Required exact label.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// Required label substring.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub label_contains: Option<String>,
    /// Required exact widget value.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<WidgetValue>,
    /// Required substring in the value's text projection.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value_text_contains: Option<String>,
    /// Whether scroll state must be initialized and stable.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scroll_ready: Option<bool>,
    /// Required stable scroll position.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scroll_at: Option<crate::types::ScrollAtCondition>,
    /// Required value inside widget data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub data: Option<crate::types::DataCondition>,
}

impl WidgetCondition {
    /// Require a widget-data value at an RFC 6901 pointer.
    pub fn data(pointer: impl Into<String>, equals: impl Into<Value>) -> Self;

    /// Require an exact widget label.
    pub fn label(label: impl Into<String>) -> Self;

    /// Require the widget to exist.
    pub fn present() -> Self;

    /// Require stable scroll metadata at the requested offset.
    pub fn scroll_at(offset: impl Into<Vec2>, tolerance: f32) -> Self;

    /// Require stable, initialized scroll metadata.
    pub fn scroll_ready() -> Self;

    /// Validate combinations and nested condition values.
    pub fn validate(&self) -> Result<(), String>;

    /// Require an exact widget value.
    pub fn value(value: WidgetValue) -> Self;

    /// Require the widget to exist and be visible.
    pub fn visible() -> Self;
}

impl JsonSchema for WidgetCondition {}

/// One font used by a captured galley.
#[derive(Clone, Debug, Deserialize<'de>, PartialEq, Serialize)]
pub struct WidgetFont {
    /// Egui font family name.
    pub family: String,
    /// Font size in logical points.
    pub size: f32,
}

impl JsonSchema for WidgetFont {}

/// Layout metadata captured for a widget when available.
#[derive(Clone, Debug, Deserialize<'de>, Serialize)]
pub struct WidgetLayout {
    /// Desired size of the widget before layout constraints.
    pub desired_size: Vec2,
    /// Actual size assigned to the widget.
    pub actual_size: Vec2,
    /// Clip rect for the widget at layout time.
    pub clip_rect: Rect,
    /// Whether any part of the widget is clipped.
    pub clipped: bool,
    /// Whether the widget extends beyond its allocated layout slot.
    pub overflow: bool,
    /// Available rect before the widget was laid out.
    pub available_rect: Rect,
    /// Visible fraction of the widget within the clip rect.
    pub visible_fraction: f32,
    /// Exact text layout painted by the widget, when the caller supplies its
    /// galley.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub text: Option<WidgetTextLayout>,
}

impl JsonSchema for WidgetLayout {}

/// Metadata for a widget used during tracking and layout analysis.
#[derive(Clone, Debug, Default)]
pub struct WidgetMeta {
    /// Role taxonomy entry with the metadata that the role requires.
    pub role: WidgetRoleMeta,
    /// Optional label.
    pub label: Option<String>,
    /// Optional widget value for stateful controls.
    pub value: Option<WidgetValue>,
    /// Structured app-domain metadata attached to this widget.
    pub data: Option<Value>,
    /// Optional layout metadata.
    pub layout: Option<WidgetLayout>,
    /// Whether the widget is visible to automation.
    ///
    /// This defaults to `false`, which hides the widget from every default
    /// lookup, so set it on every recorded widget. Response-backed helpers pass
    /// `ui.is_visible() && ui.is_rect_visible(rect)`; a painter-drawn rect has
    /// no other visibility signal, so it must state its own.
    pub visible: bool,
    /// Whether the widget accepts interaction.
    ///
    /// `None` takes the value from the `egui::Response` when there is one, and
    /// treats a response-free published rect as enabled.
    pub enabled: Option<bool>,
    /// Optional explicit rect override.
    pub rect: Option<egui::Rect>,
    /// Optional explicit interaction rect override.
    pub interact_rect: Option<egui::Rect>,
}

impl WidgetMeta {
    /// Attach structured app-domain data from any serializable value.
    pub fn with_data<T: Serialize>(self, data: T) -> Self;
}

/// Min/max bounds for a numeric widget.
///
/// The bounds are `f64` even though `DevUiExt` sliders and drag values take
/// `f32` or `i32`. Scripts see one numeric type, so every recorded range widens
/// to the type that carries all of them without loss.
#[derive(Clone, Copy, Debug, Deserialize<'de>, PartialEq, Serialize)]
pub struct WidgetRange {
    /// Minimum allowed value.
    pub min: f64,
    /// Maximum allowed value.
    pub max: f64,
}

impl WidgetRange {
    /// Check whether the range contains the provided value.
    pub fn contains(self, value: f64) -> bool;
}

impl JsonSchema for WidgetRange {}

/// Widget reference used in tool calls.
///
/// Matching rules:
/// - `id` is the canonical widget selector.
/// - `viewport_id` acts as an additional selector to narrow matches.
#[derive(Clone, Debug, Deserialize<'de>, Serialize)]
pub struct WidgetRef {
    /// Canonical widget id.
    ///
    /// If instrumentation provides an explicit id, eguidev uses it verbatim.
    /// Otherwise eguidev generates an opaque hex id that is best-effort stable
    /// within the current app session.
    pub id: String,
    /// Optional viewport selector (`root` or `vp:...`).
    #[serde(default)]
    pub viewport_id: Option<String>,
}

impl JsonSchema for WidgetRef {}

/// Widget role taxonomy for automation and scripting filters.
#[derive(Clone, Debug, Default, Deserialize<'de>, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum WidgetRole {
    Button,
    Link,
    Image,
    Label,
    TextEdit,
    Slider,
    Checkbox,
    ComboBox,
    Radio,
    DragValue,
    Toggle,
    Selectable,
    Separator,
    Spinner,
    ScrollArea,
    MenuButton,
    CollapsingHeader,
    Window,
    ProgressBar,
    ColorPicker,
    #[default]
    Unknown,
}

#[doc(hidden)]
impl JsonSchema for WidgetRole {}

/// Role taxonomy entry together with the metadata that the role requires.
///
/// Instrumentation authors this type; the registry records the flat
/// [`WidgetRole`] and [`RoleState`] that it projects. Every role that can carry
/// metadata has its own variant, so a scroll area cannot be recorded without a
/// content size and a slider cannot be recorded without a range. `Plain` is
/// only for roles that carry no metadata at all, such as a label or a
/// separator; a button with no known selection state is
/// `Button { selected: None }`, never `Plain(WidgetRole::Button)`.
#[derive(Clone, Debug, Default, PartialEq)]
pub enum WidgetRoleMeta {
    /// A role that carries no role-specific metadata.
    Plain(WidgetRole),
    /// Scroll area with its current geometry.
    ScrollArea {
        /// Current scroll offset.
        offset: Vec2,
        /// Viewport size available to the scroll contents.
        viewport_size: Vec2,
        /// Total content size within the scroll area.
        content_size: Vec2,
    },
    /// Slider with its allowed range.
    Slider {
        /// Allowed numeric range.
        range: WidgetRange,
    },
    /// Drag value, optionally constrained to a range.
    DragValue {
        /// Allowed numeric range when the app constrains one.
        range: Option<WidgetRange>,
    },
    /// Combo box with its option labels.
    ComboBox {
        /// Available option labels.
        options: Vec<String>,
    },
    /// Button, optionally carrying a selected state.
    Button {
        /// Whether the button is in a selected state, when the app tracks one.
        selected: Option<bool>,
    },
    /// Checkbox, optionally carrying a third visual state.
    Checkbox {
        /// Whether the checkbox is visually indeterminate, when the app tracks
        /// it.
        indeterminate: Option<bool>,
    },
    /// Text edit with its input configuration.
    TextEdit {
        /// Whether the edit is multiline.
        multiline: bool,
        /// Whether the edit masks its input.
        password: bool,
    },
}

impl WidgetRoleMeta {
    /// Project the flat taxonomy entry that scripts filter on.
    pub fn role(&self) -> WidgetRole;
}

/// Live widget snapshot exposed to scripting surfaces.
///
/// `(viewport_id, id)` is the one widget identity across handles, states,
/// dumps, deltas, waits, and error details, so a state that a wait returns
/// names its own widget without a second lookup.
#[derive(Clone, Debug, Deserialize<'de>, Serialize)]
pub struct WidgetState {
    /// Canonical widget id.
    pub id: String,
    /// Id of the viewport that holds the widget.
    pub viewport_id: String,
    /// Parent widget id in the same viewport, when recorded.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<String>,
    /// Child widget ids in the same viewport, in registry order.
    #[serde(default)]
    pub child_ids: Vec<String>,
    /// Widget rect.
    pub rect: Rect,
    /// Widget interaction rect.
    pub interact_rect: Rect,
    /// Role taxonomy entry.
    pub role: WidgetRole,
    /// Optional label.
    pub label: Option<String>,
    /// Optional widget value for stateful controls.
    pub value: Option<WidgetValue>,
    /// Structured app-domain metadata attached to this widget.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub data: Option<Value>,
    /// String representation of the widget value. Empty string when value is
    /// `None`. For `Bool` → `"true"`/`"false"`, `Float` → decimal, `Int` →
    /// decimal, `Text` → verbatim.
    pub value_text: String,
    /// Optional layout metadata.
    pub layout: Option<WidgetLayout>,
    /// Optional scroll metadata for scroll areas.
    #[serde(rename = "scroll_state")]
    pub scroll: Option<ScrollAreaMeta>,
    /// Optional numeric range for sliders and ranged drag values.
    pub range: Option<WidgetRange>,
    /// Optional option labels for combo boxes.
    pub options: Option<Vec<String>>,
    /// Optional selected/toggled state for selected-aware buttons.
    pub selected: Option<bool>,
    /// Optional third visual state for indeterminate checkboxes.
    pub indeterminate: Option<bool>,
    /// Optional multiline flag for text edits.
    pub multiline: Option<bool>,
    /// Optional password-masking flag for text edits.
    ///
    /// Masking is presentation only. [`Self::value`] still holds the cleartext.
    pub password: Option<bool>,
    /// Whether the widget is enabled.
    pub enabled: bool,
    /// Whether the widget is visible.
    pub visible: bool,
    /// Whether the widget reported egui focus in the captured frame (may lag
    /// keyboard focus).
    pub focused: bool,
    /// Whether another egui layer covers the widget's action point. See
    /// [`WidgetState::covered`].
    pub covered: bool,
}

impl From<&WidgetRegistryEntry> for WidgetState {}

impl JsonSchema for WidgetState {}

/// Captured text layout from the galley that a widget painted.
#[derive(Clone, Debug, Deserialize<'de>, Serialize)]
pub struct WidgetTextLayout {
    /// Fonts used by the galley's layout sections.
    pub fonts: Vec<WidgetFont>,
    /// Painted lines in visual order.
    pub lines: Vec<WidgetTextLine>,
    /// Height of the first painted line.
    pub line_height: f32,
    /// Whether egui removed text because of its row limit.
    pub elided: bool,
}

impl JsonSchema for WidgetTextLayout {}

/// One painted line from a captured galley.
#[derive(Clone, Debug, Deserialize<'de>, Serialize)]
pub struct WidgetTextLine {
    /// Text on this line.
    pub text: String,
    /// Painted line width in logical points.
    pub width: f32,
}

impl JsonSchema for WidgetTextLine {}

/// Captured widget value for stateful controls.
#[derive(Clone, Debug, Deserialize<'de>, PartialEq, Serialize)]
pub enum WidgetValue {
    /// Boolean value from checkboxes/toggles.
    Bool(bool),
    /// Floating-point value from sliders/drag values.
    Float(f64),
    /// Integer value from drag values/combos.
    Int(i64),
    /// Text value from text edits.
    Text(String),
}

impl WidgetValue {
    /// String representation matching Luau `tostring()` semantics.
    pub fn to_text(&self) -> String;
}

impl From<&str> for WidgetValue {}

impl From<String> for WidgetValue {}

impl From<bool> for WidgetValue {}

impl From<f64> for WidgetValue {}

impl From<i64> for WidgetValue {}

#[doc(hidden)]
impl JsonSchema for WidgetValue {}

/// Begin a container scope with an explicit id.
///
/// Every widget recorded while the guard lives takes `id` as its parent. Use
/// this when the container widget itself is recorded elsewhere, such as a
/// window whose response is only available after its contents have rendered.
/// Use [`container`] when the scope and the container widget can be recorded
/// together, and [`publish_rect_container`] for a painter-drawn parent.
pub fn begin_container(ui: &Ui, id: impl Into<String>) -> ContainerGuard;

/// Capture layout metadata for an already-rendered custom widget response.
pub fn capture_layout(ui: &Ui, response: &Response) -> WidgetLayout;

/// Capture layout metadata plus the exact galley that a text widget painted.
pub fn capture_layout_with_galley(ui: &Ui, response: &Response, galley: &Galley) -> WidgetLayout;

/// Run a closure within a container scope with an explicit id.
///
/// The container is registered as a widget so it is discoverable via `parent()`
/// and `children()`.
pub fn container<R>(
    ui: &mut Ui,
    id: impl Into<String>,
    add_contents: impl FnOnce(&mut Ui) -> R,
) -> R;

/// Wrap one viewport frame and register `container_id` as its root container.
///
/// Call this once for each rendered viewport pass, and render all instrumented
/// widgets for that pass inside `add_contents`. Consume pending fixture state
/// inside the closure too, so its frame epoch covers the state being rendered.
/// If the viewport has a semantic
/// name, call `name_viewport` from inside `add_contents` so the active frame is
/// already installed.
pub fn frame_scope<R>(
    devmcp: &DevMcp,
    ui: &mut Ui,
    container_id: impl Into<String>,
    add_contents: impl FnOnce(&mut Ui) -> R,
) -> R;

/// Register a semantic name for the viewport currently rendering in `ctx`.
///
/// Call this every frame from inside that viewport's instrumented pass, after
/// `FrameGuard` or `frame_scope` has made the frame active. Calls outside an
/// active instrumentation frame are ignored, which keeps production rendering
/// code usable when DevMCP is disabled.
pub fn name_viewport(ctx: &Context, name: impl Into<String>);

/// Publish a painter-drawn rect and open a container scope with the same id.
///
/// This is the documented form for a painter-drawn hierarchy. Every rect that
/// [`publish_rect_meta`] publishes while the returned guard lives becomes a
/// child of `id`, so `check_layout` reads containment as intentional structure
/// instead of one overlap per child, and the children inherit the parent's clip
/// rect. The guard pops the scope on drop.
///
/// Set [`WidgetMeta::visible`] on the canvas and on each child. A published
/// rect has no `egui::Response` to derive visibility from, and the field
/// defaults to `false`.
///
/// ```rust,ignore
/// let _board = publish_rect_container(ui, "board.canvas", board_rect, canvas_meta());
/// for (name, rect) in squares {
///     publish_rect_meta(ui, format!("board.square.{name}"), rect, square_meta());
/// }
/// ```
pub fn publish_rect_container(
    ui: &Ui,
    id: impl Into<String>,
    rect: egui::Rect,
    meta: WidgetMeta,
) -> ContainerGuard;

/// Publish metadata for a painter-drawn rect that has no `egui::Response`.
///
/// The rect is interpreted in the current UI layer and transformed to global
/// coordinates. A published rect has no `egui::Response`, so it is unfocused,
/// it is enabled unless [`WidgetMeta::enabled`] says otherwise, and it is
/// invisible to automation unless [`WidgetMeta::visible`] is set. Use
/// [`publish_rect_container`] when the rect is a parent for further rects.
pub fn publish_rect_meta(ui: &Ui, id: impl Into<String>, rect: egui::Rect, meta: WidgetMeta);

/// Consume a queued widget value override for a custom instrumented widget.
///
/// Call this every frame that the custom widget is instrumented. The runtime
/// uses that call to distinguish wired custom widgets from widgets that publish
/// a settable value but never consume queued overrides.
pub fn take_widget_value_override(ui: &Ui, id: &str) -> Option<WidgetValue>;

/// Record an already-created widget response with explicit metadata.
///
/// Use this when you hold an `egui::Response` from a custom widget and cannot
/// wrap it with [`track_widget`] or [`track_widget_with_meta`]. Prefer the
/// `DevUiExt` helpers for standard widgets.
///
/// The `track_*` functions record something that has an `egui::Response`, so
/// they can read its enabled, focused, and interaction state. The
/// `publish_rect_*` functions publish painter-drawn geometry, which has none of
/// that, so [`WidgetMeta`] must supply it.
pub fn track_response(id: impl Into<String>, response: &Response, meta: WidgetMeta);

/// Draw a custom widget and record its geometry under an explicit id.
///
/// Prefer `DevUiExt` for standard widgets. Use this when geometry is all the
/// automation needs, and [`track_widget_with_meta`] when it needs a role, a
/// label, or a value.
pub fn track_widget(
    ui: &mut Ui,
    id: impl Into<String>,
    add: impl FnOnce(&mut Ui) -> Response,
) -> Response;

/// Draw a custom widget and record it with explicit role metadata.
///
/// Use this when automation needs the role, label, or value of a custom widget.
/// Use [`track_response`] when the response already exists.
pub fn track_widget_with_meta(
    ui: &mut Ui,
    id: impl Into<String>,
    role: WidgetRoleMeta,
    label: Option<String>,
    value: Option<WidgetValue>,
    add: impl FnOnce(&mut Ui) -> Response,
) -> Response;

#[doc(hidden)]
pub mod internal {
    pub mod actions {
        #[derive(Default)]
        pub struct ActionQueue {/* private fields */}

        impl ActionQueue {
            pub fn clear_all(&self);

            pub fn clear_viewport(&self, viewport_id: ViewportId);

            pub fn drain_actions(&self, viewport_id: ViewportId, frame: u64) -> Vec<InputAction>;

            pub fn drain_commands(&self, viewport_id: ViewportId) -> Vec<ViewportCommand>;

            pub fn has_pending_actions(&self, viewport_id: ViewportId) -> bool;

            pub fn has_pending_commands(&self, viewport_id: ViewportId) -> bool;

            pub fn new() -> Self;

            pub fn pending_action_count(&self, viewport_id: ViewportId) -> usize;

            pub fn pending_command_count(&self, viewport_id: ViewportId) -> usize;

            /// Return recent pointer delivery evidence for failure diagnostics.
            pub fn pointer_trace(&self) -> Value;

            pub fn queue_action_with_timing(
                &self,
                viewport_id: ViewportId,
                timing: ActionTiming,
                action: InputAction,
            );

            pub fn queue_command(&self, viewport_id: ViewportId, command: ViewportCommand);

            pub fn stats(&self, viewport_id: ViewportId) -> ActionQueueStats;
        }

        #[derive(Clone, Copy, Debug, Default, Serialize)]
        pub struct ActionQueueStats {
            pub queued_actions: u64,
            pub drained_actions: u64,
            pub last_drain_frame: Option<u64>,
        }

        /// How many whole frames an action waits before it reaches the app.
        ///
        /// Delayed actions start counting at their first drain. Repeated drains with
        /// the same frame number do not shorten the delay.
        #[derive(Clone, Copy, Debug, Eq, PartialEq)]
        pub enum ActionTiming {
            /// Deliver at the next drain.
            Immediate,
            /// Deliver one frame after the next drain.
            AfterOneFrame,
            /// Deliver two frames after the next drain.
            AfterTwoFrames,
            /// Deliver three frames after the next drain.
            AfterThreeFrames,
        }

        #[derive(Clone, Debug)]
        pub enum InputAction {
            PointerMove {
                pos: Pos2,
            },
            PointerButton {
                pos: Pos2,
                button: egui::PointerButton,
                pressed: bool,
                modifiers: Modifiers,
            },
            Key {
                key: Key,
                pressed: bool,
                modifiers: Modifiers,
            },
            Text {
                text: String,
            },
            Paste {
                text: String,
            },
            Scroll {
                delta: Vec2,
                modifiers: Modifiers,
            },
        }

        impl InputAction {
            pub fn apply(self, raw_input: &mut RawInput);
        }
    }

    pub mod devmcp {
        pub use crate::AutomationOptions;

        pub trait RuntimeHooks: Send + Sync {
            fn as_any(&self) -> &(dyn Any + Send + Sync);

            fn on_egui_output(
                &self,
                _inner: &Inner,
                _viewport_id: ViewportId,
                _output: &FullOutput,
            ) {
            }

            fn on_frame_end(&self, _inner: &Inner, _ctx: &Context) {}

            fn on_raw_input(&self, _inner: &Inner, _events: &[Event]) {}
        }
    }

    pub mod diagnostics {
        /// Started diagnostic execution.
        pub enum DiagnosticExecution {
            /// The provider completed immediately.
            Ready(DiagnosticResult),
            /// The provider must be awaited after the UI thread drains the request.
            Queued(crate::diagnostics::DiagnosticReceiver),
        }

        impl !Sync for DiagnosticExecution {}

        /// Registry of named app diagnostic providers.
        #[derive(Clone, Debug, Default)]
        pub struct DiagnosticRegistry {/* private fields */}

        impl DiagnosticRegistry {
            /// Run every queued UI-thread diagnostic provider against the current root
            /// context.
            pub fn drain_ui(&self, ctx: &Context);

            /// Return sorted diagnostic provider names.
            pub fn names(&self) -> Vec<String>;

            /// Create an empty diagnostic registry.
            pub fn new() -> Self;

            /// Start one diagnostic provider by name.
            pub fn start(&self, name: &str) -> DiagnosticExecution;
        }
    }

    pub mod error {
        #[derive(Clone, Copy, Debug, Eq, PartialEq)]
        pub enum ErrorCode {
            InvalidArgument,
            NotFound,
            NotActionable,
            InstrumentationFault,
            Timeout,
            Unsupported,
            FixtureFailed,
            DiagnosticFailed,
            ExpectationFailed,
            Internal,
        }

        impl ErrorCode {
            pub fn as_str(self) -> &'static str;
        }

        #[derive(Clone, Debug, Display, Error)]
        pub struct ToolError {/* private fields */}

        impl ToolError {
            pub fn code(&self) -> ErrorCode;

            pub fn details(&self) -> Option<&Value>;

            pub fn message(&self) -> &str;

            pub fn new(code: ErrorCode, message: impl Into<String>) -> Self;

            pub fn with_details(self, details: Value) -> Self;
        }
    }

    pub mod fixtures {
        /// Started fixture execution.
        pub enum FixtureExecution {
            /// The fixture handler completed immediately.
            Ready(FixtureResult),
            /// The fixture handler must be awaited after the UI thread drains the
            /// request.
            Queued(crate::fixtures::UiFixtureReceiver),
        }

        impl !Sync for FixtureExecution {}

        /// Configured fixture handler.
        #[derive(Clone)]
        pub enum FixtureHandler {
            /// Runtime-thread handler.
            Runtime(Arc<dyn Fn(&FixtureCall) -> FixtureResult + Send + Sync>),
            /// UI-thread handler.
            Ui(Arc<Mutex<Box<dyn FnMut(&Context, &FixtureCall) -> FixtureResult + Send>>>),
        }
    }

    pub mod idle {
        /// Registry for the optional app idle provider.
        #[derive(Clone, Debug, Default)]
        pub struct IdleRegistry {/* private fields */}

        impl IdleRegistry {
            /// Return whether an idle provider has been configured.
            pub fn is_configured(&self) -> bool;

            /// Create an empty idle registry.
            pub fn new() -> Self;

            /// Evaluate the currently configured idle provider for settle reporting.
            pub fn status(&self) -> Option<IdleStatus>;

            /// Run the UI-thread provider at root frame end and cache its result.
            pub fn update_ui(&self, ctx: &Context, frame: u64);
        }

        /// Most recent app idle state from either a runtime or UI-thread provider.
        #[derive(Clone, Debug, Eq, PartialEq)]
        pub struct IdleStatus {
            /// Whether the app reports itself idle.
            pub idle: bool,
            /// Human-readable status detail for settle reports.
            pub detail: String,
            /// Root frame count that produced this status, for UI-thread providers.
            pub frame: Option<u64>,
        }
    }

    pub mod overlay {
        #[derive(Clone, Debug, Default)]
        pub struct OverlayDebugConfig {
            pub enabled: bool,
            pub mode: OverlayDebugMode,
            pub scope: Option<WidgetRef>,
            pub options: OverlayDebugOptions,
        }

        #[derive(Clone, Copy, Debug, Eq, PartialEq)]
        pub enum OverlayDebugMode {
            Bounds,
            Margins,
            Clipping,
            Overlaps,
            Focus,
            Layers,
            Containers,
        }

        #[derive(Clone, Debug, Default)]
        pub struct OverlayDebugOptions {
            pub show_labels: bool,
            pub show_sizes: bool,
            pub label_font_size: f32,
            pub bounds_color: Color32,
            pub clip_color: Color32,
            pub overlap_color: Color32,
        }

        #[derive(Clone, Debug)]
        pub struct OverlayEntry {
            pub rect: egui::Rect,
            pub color: Color32,
            pub stroke_width: f32,
        }

        #[derive(Default)]
        pub struct OverlayManager {/* private fields */}

        impl OverlayManager {
            pub fn clear_overlay_debug_config(&self, viewport_id: ViewportId);

            pub fn clear_overlays(&self);

            pub fn clear_transient_state(&self);

            pub fn clear_viewport_overlays(&self, viewport_id: ViewportId);

            pub fn new() -> Self;

            pub fn overlay_debug_config(&self, viewport_id: ViewportId) -> OverlayDebugConfig;

            pub fn paint_overlays(
                &self,
                ctx: &Context,
                widgets: &WidgetRegistry,
                viewports: &ViewportState,
            );

            pub fn remove_overlay(&self, viewport_id: ViewportId, key: &str);

            pub fn set_overlay(&self, viewport_id: ViewportId, key: String, overlay: OverlayEntry);

            pub fn set_overlay_debug_config(
                &self,
                viewport_id: ViewportId,
                config: OverlayDebugConfig,
            );
        }

        pub fn parse_color(value: &str) -> Option<Color32>;

        pub fn rect_intersection(first: Rect, second: Rect) -> Option<Rect>;

        pub fn rect_size(rect: Rect) -> Vec2;
    }

    pub mod presentation {
        /// Presentation requested for one automation connection or launcher.
#[derive(Clone, Copy, Debug, Default, Deserialize<'de>, Eq, PartialEq, Serialize)]
#[serde(rename_all = "lowercase")]
        pub enum Presentation {
            /// Keep the app out of the foreground while automation is connected.
            #[default]
            Background,
            /// Preserve the app's ordinary foreground presentation.
            Foreground,
        }

        impl Presentation {
            /// Return the wire spelling used in the initialize capability and status
            /// payload.
            pub const fn as_str(self) -> &'static str;
        }

        /// Serializable macOS presentation diagnostics reported by the runtime.
#[derive(Clone, Debug, Default, Deserialize<'de>, Eq, PartialEq, Serialize)]
        pub struct PresentationStatus {
            /// Presentation requested when the automation connection was initialized.
            pub requested_presentation: Presentation,
            /// Activation policy observed in the app process, when available.
            pub observed_activation_policy: Option<String>,
            /// Absolute executable path reported by the app process, when available.
            pub executable: Option<String>,
            /// Enclosing application bundle, when the executable is bundled.
            pub bundle_root: Option<String>,
            /// Application bundle identifier, when available.
            pub bundle_identifier: Option<String>,
        }

        impl PresentationStatus {
            /// Build the initial status before the runtime health payload is available.
            pub const fn requested(requested_presentation: Presentation) -> Self;
        }

        /// Private experimental MCP capability used to negotiate app presentation.
        pub const EXPERIMENTAL_PRESENTATION_CAPABILITY: &str = "eguidev.presentation";
    }

    pub mod registry {
        #[derive(Debug, Default)]
        pub struct Inner {
            pub actions: ActionQueue,
            pub viewports: ViewportState,
            pub widgets: WidgetRegistry,
            pub overlays: OverlayManager,
            pub last_action_frame: AtomicU64,
            pub fixtures: crate::fixtures::FixtureManager,
            pub diagnostics: DiagnosticRegistry,
            pub idle: IdleRegistry,
            /* private fields */
        }

        impl Inner {
            pub const UNCONSUMED_OVERRIDE_FRAME_GRACE: u64 = 2;
            /// Count one settled automation frame. Discarded layout passes do not
            /// publish automation state or increment this count.
            pub fn advance_frame(&self);

            pub fn automation_options(&self) -> AutomationOptions;

            pub fn begin_fixture_epoch(&self) -> u64;

            pub fn begin_frame(&self, viewport_id: ViewportId);

            pub fn capture_context(&self, viewport_id: ViewportId, ctx: &Context);

            pub fn clear_all(&self);

            pub fn clear_overlay_debug_config(&self, viewport_id: ViewportId);

            pub fn clear_overlays(&self);

            pub fn clear_viewport_overlays(&self, viewport_id: ViewportId);

            pub fn clear_widget_value_update_if_matches(
                &self,
                viewport_id: ViewportId,
                id: &str,
                value: &WidgetValue,
            );

            pub fn context_for(&self, viewport_id: ViewportId) -> Option<Context>;

            pub fn dismiss_transient_ui(&self, viewport_id: Option<ViewportId>);

            /// Enter a viewport frame. Returns true when this is the outermost begin.
            pub fn enter_viewport_frame(&self, viewport_id: ViewportId) -> bool;

            /// Exit a viewport frame. Returns true when this is the matching outermost
            /// end.
            pub fn exit_viewport_frame(&self, viewport_id: ViewportId) -> bool;

            pub fn expired_widget_value_update_error(
                &self,
                viewport_id: ViewportId,
                widget_id: Option<&str>,
            ) -> Option<ToolError>;

            pub fn finish_frame_fixture_epoch(&self, viewport_id: ViewportId) -> Option<u64>;

            pub fn fixture_epoch(&self) -> u64;

            /// Drop heavy per-viewport maps for non-root viewports that left the live
            /// set.
            pub fn forget_dead_viewports(&self);

            pub fn frame_count(&self) -> u64;

            pub fn frame_health(&self, viewport_id: ViewportId) -> Option<FrameHealth>;

            pub fn has_context(&self) -> bool;

            pub fn mark_widget_value_consumer(&self, viewport_id: ViewportId, id: &str);

            pub fn new() -> Self;

            pub fn next_request_id(&self) -> u64;

            pub fn paint_overlays(&self, ctx: &Context);

            pub fn queue_action(&self, viewport_id: ViewportId, action: InputAction);

            pub fn queue_action_with_timing(
                &self,
                viewport_id: ViewportId,
                timing: ActionTiming,
                action: InputAction,
            );

            pub fn queue_command(&self, viewport_id: ViewportId, command: ViewportCommand);

            pub fn queue_widget_value_update(
                &self,
                viewport_id: ViewportId,
                id: String,
                value: WidgetValue,
            );

            pub fn remember_context(&self, viewport_id: ViewportId, ctx: &Context);

            pub fn remove_overlay(&self, viewport_id: ViewportId, key: &str);

            pub fn request_repaint(&self);

            pub fn request_repaint_all(&self);

            pub fn request_repaint_of(&self, viewport_id: ViewportId);

            pub fn runtime_hooks(&self) -> Option<Arc<dyn RuntimeHooks>>;

            pub fn set_automation_options(&self, options: AutomationOptions);

            pub fn set_overlay(&self, viewport_id: ViewportId, key: String, overlay: OverlayEntry);

            pub fn set_overlay_debug_config(
                &self,
                viewport_id: ViewportId,
                config: OverlayDebugConfig,
            );

            pub fn set_runtime_hooks(&self, hooks: Arc<dyn RuntimeHooks>);

            pub fn set_scroll_override(
                &self,
                viewport_id: ViewportId,
                widget_id: u64,
                offset: egui::Vec2,
            );

            pub fn set_shutdown_handler(&self, handler: Option<Arc<dyn Fn() + Send + Sync>>);

            pub fn set_verbose_logging(&self, verbose_logging: bool);

            pub fn shutdown_handler(&self) -> Option<Arc<dyn Fn() + Send + Sync>>;

            /// Start applying a validated fixture by calling the registered handler.
            pub fn start_fixture(&self, call: FixtureCall) -> FixtureExecution;

            pub fn take_scroll_override(
                &self,
                viewport_id: ViewportId,
                widget_id: u64,
            ) -> Option<egui::Vec2>;

            pub fn take_widget_value_update(
                &self,
                viewport_id: ViewportId,
                id: &str,
            ) -> Option<WidgetValue>;

            pub fn verbose_logging(&self) -> bool;
        }

        pub fn lock<'a, T>(mutex: &'a Mutex<T>, label: &'static str) -> MutexGuard<'a, T>;

        pub fn viewport_id_to_string(viewport_id: ViewportId) -> String;
    }

    pub mod tree {
        /// Collect a widget and all descendant widgets from a flat registry snapshot.
        pub fn collect_subtree(
            widgets: &[WidgetRegistryEntry],
            root: &WidgetRegistryEntry,
        ) -> Vec<WidgetRegistryEntry>;
    }

    pub mod types {
        pub use crate::{
            ActionOptions, DragOptions, FixtureCall, FixtureError, FixtureParam, FixtureParams,
            FixtureResponse, FixtureResult, FixtureSpec, FixtureTargetSpec, ParamKind,
            PointerButton, Pos2, RawInputAction, RawInputEvent, Rect, ResizeOptions, RoleState,
            ScrollAlign, ScrollAreaMeta, Vec2, ViewportCondition, ViewportNameError, ViewportSel,
            ViewportSelParseError, WaitOptions, WidgetCondition, WidgetFont, WidgetLayout,
            WidgetRange, WidgetRef, WidgetRole, WidgetRoleMeta, WidgetState, WidgetTextLayout,
            WidgetTextLine, WidgetValue,
        };

        /// Keyboard modifier state.
#[derive(Clone, Copy, Debug, Default, Deserialize<'de>, Serialize)]
        pub struct Modifiers {
            /// Ctrl key pressed.
            #[serde(default)]
            pub ctrl: bool,
            /// Shift key pressed.
            #[serde(default)]
            pub shift: bool,
            /// Alt key pressed.
            #[serde(default)]
            pub alt: bool,
            /// Command key pressed.
            #[serde(default)]
            pub command: bool,
        }

        impl From<Modifiers> for egui::Modifiers {}

        impl From<egui::Modifiers> for Modifiers {}

        impl JsonSchema for Modifiers {}

        /// Widget registry entry captured per frame.
#[derive(Clone, Debug, Deserialize<'de>, Serialize)]
        pub struct WidgetRegistryEntry {
            /// Canonical widget id.
            pub id: String,
            /// Whether the id was explicitly provided by instrumentation.
            #[serde(skip_serializing, skip_deserializing)]
            #[schemars(skip)]
            pub explicit_id: bool,
            /// Raw egui widget id used for low-level engine interactions.
            #[serde(skip_serializing, skip_deserializing)]
            #[schemars(skip)]
            pub native_id: u64,
            /// Viewport id string.
            pub viewport_id: String,
            /// Layer id rendered as a stable string (internal use only, e.g. debug
            /// overlay).
            #[serde(skip_serializing, skip_deserializing)]
            #[schemars(skip)]
            pub layer_id: String,
            /// Paint order of the widget's layer, where a larger value paints later
            /// (internal use only).
            #[serde(skip_serializing, skip_deserializing)]
            #[schemars(skip)]
            pub layer_order: u8,
            /// Widget rect.
            pub rect: Rect,
            /// Widget interaction rect.
            pub interact_rect: Rect,
            /// Role taxonomy entry.
            pub role: WidgetRole,
            /// Optional label.
            pub label: Option<String>,
            /// Optional widget value for stateful controls.
            pub value: Option<WidgetValue>,
            /// Structured app-domain metadata attached to this widget.
            #[serde(default, skip_serializing_if = "Option::is_none")]
            pub data: Option<Value>,
            /// Optional layout metadata.
            pub layout: Option<WidgetLayout>,
            /// Optional role-specific metadata encoded as a nested enum.
            #[serde(default)]
            pub role_state: Option<RoleState>,
            /// Optional parent id for container scoping.
            pub parent_id: Option<String>,
            /// Whether the widget is enabled.
            pub enabled: bool,
            /// Whether the widget is visible.
            pub visible: bool,
            /// Whether the widget reported egui focus in the captured frame (may lag
            /// keyboard focus).
            pub focused: bool,
            /// Whether another egui layer covers the widget's action point (the
            /// center of `interact_rect`), so a pointer action here would route to
            /// that layer instead. `false` when no layer, or only the widget's own
            /// layer, sits at that point.
            pub covered: bool,
        }

        impl WidgetRegistryEntry {
            /// Selected-on projection used by widget state, dumps, and list filters.
            pub fn selected(&self) -> Option<bool>;
        }

        impl JsonSchema for WidgetRegistryEntry {}
    }

    pub mod ui_ext {
        /// Parse a CSS-style `#RRGGBB` or `#RRGGBBAA` color literal.
        pub fn parse_color_hex(value: &str) -> Option<Color32>;
    }

    pub mod viewports {
        #[derive(Clone, Copy, Debug)]
        pub struct FrameHealth {
            pub viewport_id: ViewportId,
            pub frame_count: u64,
            pub last_completed: Instant,
        }

        impl FrameHealth {
            pub fn age(&self) -> Duration;

            pub fn frames_observed_since(&self, start_frame: u64) -> u64;
        }

        #[derive(Clone, Debug)]
        pub struct InputSnapshot {
            pub pixels_per_point: f32,
            pub pointer_pos: Option<Pos2>,
        }

        #[derive(Clone, Copy, Debug)]
        pub struct OutputSnapshot {
            pub cursor_icon: CursorIcon,
        }

        #[derive(Clone, Debug, Default)]
        pub struct PlatformViewportState {
            pub title: Option<String>,
            pub window_number: Option<u32>,
            pub os_minimized: Option<bool>,
            pub os_occluded: Option<bool>,
            pub os_title_visible: Option<bool>,
        }

        #[derive(Clone, Debug, Deserialize<'de>, Serialize)]
        pub struct ViewportSnapshot {
            pub viewport_id: String,
            pub name: Option<String>,
            pub inner_size: Vec2,
            pub outer_pos: Option<Pos2>,
            pub outer_size: Option<Vec2>,
            pub pixels_per_point: f32,
            pub focused: bool,
            pub title: Option<String>,
            pub parent_viewport_id: Option<String>,
            pub minimized: Option<bool>,
            pub occluded: Option<bool>,
            pub os_minimized: Option<bool>,
            pub os_occluded: Option<bool>,
            pub os_title_visible: Option<bool>,
            pub maximized: Option<bool>,
            pub fullscreen: Option<bool>,
        }

        impl JsonSchema for ViewportSnapshot {}

        #[derive(Default)]
        pub struct ViewportState {/* private fields */}

        impl ViewportState {
            pub fn capture_input_snapshot(
                &self,
                ctx: &Context,
                fixture_epoch: u64,
                frame_count: u64,
            );

            pub fn capture_snapshot(
                &self,
                viewport_id: ViewportId,
            ) -> Option<crate::viewports::CaptureSnapshot>;

            pub fn frame_health(&self, viewport_id: ViewportId) -> Option<FrameHealth>;

            pub fn frame_health_snapshot(&self) -> Vec<FrameHealth>;

            pub fn frames_observed_since(
                &self,
                viewport_id: ViewportId,
                start_frame: u64,
            ) -> Option<u64>;

            pub fn has_viewport_snapshot(&self, viewport_id: ViewportId) -> bool;

            pub fn input_snapshot(&self, viewport_id: ViewportId) -> Option<InputSnapshot>;

            pub fn is_live_viewport(&self, viewport_id: ViewportId) -> bool;

            pub fn live_viewport_ids(&self) -> Option<HashSet<ViewportId>>;

            pub fn merge_platform_state(&self, states: &[PlatformViewportState]);

            pub fn name_viewport(&self, viewport_id: ViewportId, name: String);

            pub fn new() -> Self;

            pub fn output_snapshot(&self, viewport_id: ViewportId) -> Option<OutputSnapshot>;

            pub fn record_input_snapshot(
                &self,
                viewport_id: ViewportId,
                snapshot: InputSnapshot,
                fixture_epoch: u64,
                frame_count: u64,
            );

            pub fn record_output_snapshot(&self, viewport_id: ViewportId, snapshot: OutputSnapshot);

            pub fn recorded_frame_count(&self, viewport_id: ViewportId) -> u64;

            pub fn remember_viewport_id(&self, viewport_id: ViewportId);

            pub fn resolve_viewport_id(
                &self,
                viewport_id: Option<String>,
            ) -> Result<ViewportId, ToolError>;

            pub fn update_viewports(&self, ctx: &Context);

            pub fn viewport_name_error(&self) -> Option<ToolError>;

            /// Current viewport snapshots, excluding closed secondary viewports.
            pub fn viewports_snapshot(&self) -> Vec<ViewportSnapshot>;
        }
    }

    pub mod widget_registry {
        pub use crate::WidgetMeta;

        #[derive(Default)]
        pub struct WidgetRegistry {/* private fields */}

        impl WidgetRegistry {
            pub fn child_ids_of(&self, viewport_id: ViewportId, parent_id: &str) -> Vec<String>;

            pub fn clear_registry(&self, viewport_id: ViewportId);

            pub fn current_container(&self, viewport_id: ViewportId) -> Option<String>;

            pub fn duplicate_explicit_id_error(
                &self,
                viewports: &ViewportState,
            ) -> Option<ToolError>;

            pub fn finalize_registry(&self, viewport_id: ViewportId);

            pub fn new() -> Self;

            pub fn pop_container(&self, viewport_id: ViewportId);

            pub fn push_container(&self, viewport_id: ViewportId, id: String);

            pub fn record_widget(&self, viewport_id: ViewportId, entry: WidgetRegistryEntry);

            pub fn resolve_widget(
                &self,
                viewports: &ViewportState,
                viewport_id: Option<&str>,
                target: &WidgetRef,
            ) -> Result<WidgetRegistryEntry, ToolError>;

            pub fn resolve_widget_global(
                &self,
                viewports: &ViewportState,
                target: &WidgetRef,
            ) -> Result<WidgetRegistryEntry, ToolError>;

            pub fn widget_list(&self, viewport_id: ViewportId) -> Vec<WidgetRegistryEntry>;
        }

        pub fn record_widget(
            widgets: &WidgetRegistry,
            id: String,
            response: &Response,
            meta: WidgetMeta,
        );
    }
}
