// @generated by `ruskel-snapshot`; do not edit.

pub mod eguidev_runtime {
    //! Native embedded runtime for `eguidev`.
    //!
    //! `eguidev_runtime` attaches the in-process automation server, script
    //! evaluation, screenshots, and smoke runner to an inert [`eguidev::DevMcp`]
    //! handle.
    //!
    //! For `eframe` applications, the most reliable integration pattern is:
    //!
    //! - choose `eframe::Renderer::Glow` for automation runs when possible
    //! - register a fixture handler with [`eguidev::DevMcp::on_fixture_runtime`] or
    //!   [`eguidev::DevMcp::on_fixture_ui`]
    //! - wrap every frame in [`eguidev::FrameGuard`], which registers an egui
    //!   plugin on the first frame to inject input automatically
    //!
    //! The `wgpu` backend can exhibit idle-frame stalls in some `eframe`
    //! integrations, so the demo and examples prefer `Glow`.

    pub mod smoke {
        //! Smoketest suite runner for Luau scripts against a live DevMCP app.

        /// Result of a single script execution.
        pub struct ScriptResult {
            /// One-based round index for repeated suite runs.
            pub round: u32,
            /// Forward-slash-normalized relative script path, or `<suite>` for
            /// suite-level failures.
            pub path: String,
            /// Final script status.
            pub status: ScriptStatus,
            /// Script runtime in milliseconds. Skipped scripts report `0`.
            pub elapsed_ms: u64,
            /// Failure or skip message when present.
            pub message: Option<String>,
            /// Logs emitted by the script.
            pub logs: Vec<String>,
            /// Fixtures applied during the script.
            pub fixtures: Vec<crate::FixtureApplication>,
            /// Undismissed egui diagnostics retained by the evaluation.
            pub egui_diagnostics: crate::EguiDiagnosticBatch,
            /// Verbose failure details from the script runtime.
            pub details: Option<String>,
        }

        /// Input passed to a caller-supplied per-script smoke executor.
        pub struct ScriptRunRequest {
            /// Forward-slash-normalized relative script path used for diagnostics.
            pub path: String,
            /// One-based round index for repeated suite runs.
            pub round: u32,
            /// Luau source code loaded from disk.
            pub source: String,
            /// Optional per-script timeout in milliseconds.
            pub timeout_ms: Option<u64>,
            /// Suite-wide args passed to the script.
            pub args: crate::ScriptArgs,
        }

        /// Outcome for an individual smoketest script.
        pub enum ScriptStatus {
            /// Script completed successfully.
            Pass,
            /// Script failed or the suite hit a setup error.
            Fail,
            /// Script was skipped because the suite timed out or fail-fast triggered.
            Skip,
        }

        /// Configuration for a smoketest suite run.
        pub struct SuiteConfig {
            /// Directory containing `.luau` test scripts.
            pub suite_dir: std::path::PathBuf,
            /// Explicit script paths to run. Empty means discover all `.luau` files
            /// under `suite_dir` recursively in lexicographic order.
            pub scripts: Vec<std::path::PathBuf>,
            /// Discovery glob filters matched against display paths. Empty means all
            /// discovered scripts. Cannot be combined with explicit `scripts`.
            pub only: Vec<String>,
            /// Wall-clock deadline for the entire suite.
            pub suite_timeout: std::time::Duration,
            /// Per-script timeout. `None` uses the script-eval default.
            pub script_timeout: Option<std::time::Duration>,
            /// Stop after the first failure.
            pub fail_fast: bool,
            /// Fail scripts that leave egui identity diagnostics undismissed.
            pub fail_on_egui_diagnostics: bool,
            /// Repetition behavior for the selected suite.
            pub run_mode: SuiteRunMode,
            /// Args passed to every script in the suite.
            pub args: crate::ScriptArgs,
        }

        /// Result of running a full suite.
        pub struct SuiteResult {
            /// Per-script results in execution order.
            pub results: Vec<ScriptResult>,
            /// Per-round timings.
            pub rounds: Vec<SuiteRoundResult>,
            /// Maximum number of rounds requested for this suite invocation.
            pub requested_rounds: u32,
            /// Total suite runtime in milliseconds.
            pub elapsed_ms: u64,
        }

        /// Runtime summary for one repeated suite round.
        pub struct SuiteRoundResult {
            /// One-based round index.
            pub round: u32,
            /// Round runtime in milliseconds.
            pub elapsed_ms: u64,
        }

        /// Repetition behavior for one smoke suite invocation.
        pub enum SuiteRunMode {
            /// Run the selected scripts this many times. Values below 1 are treated as
            /// one round.
            Repeat(u32),
            /// Repeat until the first failure, stopping after at most this many rounds.
            /// Values below 1 are treated as one round.
            UntilFail(u32),
        }

        /// Discovered smoke script metadata for list mode.
        pub struct SuiteScriptInfo {
            /// Forward-slash-normalized display path.
            pub path: String,
            /// Script file size in bytes.
            pub size: u64,
        }

        /// Discover the selected smoke scripts without running them.
        pub fn discover_suite_scripts(config: &SuiteConfig) -> io::Result<Vec<SuiteScriptInfo>> {}

        /// Run a smoketest suite against a live `DevMcp` instance.
        ///
        /// Blocks the calling thread on `handle` for each script. Prefer
        /// [`run_suite_with`] when the caller already owns the async context.
        pub fn run_suite(
            devmcp: &crate::DevMcp,
            handle: &tokio::runtime::Handle,
            config: &SuiteConfig,
        ) -> SuiteResult {
        }

        /// Run a smoketest suite through a caller-supplied script executor.
        pub fn run_suite_with<F>(config: &SuiteConfig, execute: F) -> SuiteResult
        where
            F: FnMut(ScriptRunRequest) -> Result<crate::ScriptEvalOutcome, String>, {
        }

        impl Clone for ScriptResult {
            fn clone(&self) -> ScriptResult {}
        }

        impl Debug for ScriptResult {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
        }

        impl PartialEq for ScriptResult {
            fn eq(&self, other: &ScriptResult) -> bool {}
        }

        impl Clone for ScriptRunRequest {
            fn clone(&self) -> ScriptRunRequest {}
        }

        impl Debug for ScriptRunRequest {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
        }

        impl PartialEq for ScriptRunRequest {
            fn eq(&self, other: &ScriptRunRequest) -> bool {}
        }

        impl Clone for ScriptStatus {
            fn clone(&self) -> ScriptStatus {}
        }

        impl Debug for ScriptStatus {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
        }

        impl Eq for ScriptStatus {
            #[doc(hidden)]
            fn assert_fields_are_eq(&self) {}
        }

        impl PartialEq for ScriptStatus {
            fn eq(&self, other: &ScriptStatus) -> bool {}
        }

        impl Clone for SuiteConfig {
            fn clone(&self) -> SuiteConfig {}
        }

        impl Debug for SuiteConfig {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
        }

        impl PartialEq for SuiteConfig {
            fn eq(&self, other: &SuiteConfig) -> bool {}
        }

        impl SuiteConfig {
            /// Apply suite-level egui diagnostic policy to one script outcome.
            pub fn apply_egui_diagnostic_policy(&self, outcome: &mut ScriptEvalOutcome) {}

            /// Maximum number of rounds this suite can run.
            pub fn round_limit(&self) -> u32 {}
        }

        impl Clone for SuiteResult {
            fn clone(&self) -> SuiteResult {}
        }

        impl Debug for SuiteResult {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
        }

        impl PartialEq for SuiteResult {
            fn eq(&self, other: &SuiteResult) -> bool {}
        }

        impl SuiteResult {
            /// Count failing scripts.
            pub fn failed(&self) -> usize {}

            /// Count passing scripts.
            pub fn passed(&self) -> usize {}

            /// Count skipped scripts.
            pub fn skipped(&self) -> usize {}

            /// Render suite results as printable lines.
            pub fn render_lines(&self, verbose: bool) -> Vec<String> {}

            /// Returns `true` when every discovered script passed.
            pub fn success(&self) -> bool {}
        }

        impl Clone for SuiteRoundResult {
            fn clone(&self) -> SuiteRoundResult {}
        }

        impl Debug for SuiteRoundResult {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
        }

        impl Eq for SuiteRoundResult {
            #[doc(hidden)]
            fn assert_fields_are_eq(&self) {}
        }

        impl PartialEq for SuiteRoundResult {
            fn eq(&self, other: &SuiteRoundResult) -> bool {}
        }

        impl Clone for SuiteRunMode {
            fn clone(&self) -> SuiteRunMode {}
        }

        impl Debug for SuiteRunMode {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
        }

        impl Eq for SuiteRunMode {
            #[doc(hidden)]
            fn assert_fields_are_eq(&self) {}
        }

        impl PartialEq for SuiteRunMode {
            fn eq(&self, other: &SuiteRunMode) -> bool {}
        }

        impl SuiteRunMode {
            /// Return the maximum number of rounds this mode can run.
            pub fn round_limit(self) -> u32 {}

            /// Run the selected scripts once.
            pub const ONCE: Self = _;
        }

        impl Clone for SuiteScriptInfo {
            fn clone(&self) -> SuiteScriptInfo {}
        }

        impl Debug for SuiteScriptInfo {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
        }

        impl Eq for SuiteScriptInfo {
            #[doc(hidden)]
            fn assert_fields_are_eq(&self) {}
        }

        impl PartialEq for SuiteScriptInfo {
            fn eq(&self, other: &SuiteScriptInfo) -> bool {}
        }

        impl Serialize for SuiteScriptInfo {
            fn serialize<__S>(
                &self,
                __serializer: __S,
            ) -> _serde::__private229::Result<__S::Ok, __S::Error>
            where
                __S: _serde::Serializer, {
            }
        }
    }

    pub use eguidev::DevMcp;
    /// One egui identity diagnostic from a completed viewport pass.
    pub struct EguiDiagnostic {
        /// Stable diagnostic kind.
        pub kind: EguiDiagnosticKind,
        /// Diagnostic severity.
        pub severity: EguiDiagnosticSeverity,
        /// Human-readable warning text.
        pub message: String,
        /// Canonical viewport selector that produced the diagnostic.
        pub viewport_id: String,
        /// Eguidev app-wide frame counter at output completion.
        pub frame: u64,
        #[serde(skip_serializing_if = "Option::is_none")]
        /// Affected rectangle when egui supplies one.
        pub rect: Option<crate::Rect>,
    }

    /// Diagnostics retained for one script evaluation.
    pub struct EguiDiagnosticBatch {
        /// Retained diagnostics in journal sequence order.
        pub entries: Vec<EguiDiagnostic>,
        /// Undismissed diagnostics overwritten before they could be returned.
        pub dropped: u64,
    }

    #[serde(rename_all = "snake_case")]
    /// Kind of identity warning emitted by egui.
    pub enum EguiDiagnosticKind {
        /// One egui ID was used for different rectangles in one pass.
        IdClash,
        /// One rectangle changed egui ID between completed passes.
        RectChangedId,
    }

    #[serde(rename_all = "snake_case")]
    /// Severity assigned to an egui diagnostic.
    pub enum EguiDiagnosticSeverity {
        /// The diagnostic reports suspicious identity behavior.
        Warning,
    }

    /// Fixture applied during a script evaluation.
    pub struct FixtureApplication {
        /// Fixture name passed to `eguidev.fixture(...)`.
        pub name: String,
        #[serde(default)]
        #[serde(skip_serializing_if = "BTreeMap::is_empty")]
        /// Validated fixture parameters, including defaults supplied by the fixture
        /// spec.
        pub params: std::collections::BTreeMap<String, crate::types::WidgetValue>,
    }

    pub use eguidev::Rect;
    #[serde(untagged)]
    /// Scalar value that can be injected into the global Luau `args` table.
    pub enum ScriptArgValue {
        /// String-valued script arg.
        String(String),
        /// Integer-valued script arg.
        Int(i64),
        /// Floating-point script arg.
        Float(f64),
        /// Boolean-valued script arg.
        Bool(bool),
    }

    /// Deterministic map of script args exposed to Luau as the global `args` table.
    pub type ScriptArgs = std::collections::BTreeMap<String, ScriptArgValue>;

    /// Assertion outcome recorded during script execution.
    pub struct ScriptAssertion {
        /// Whether the assertion passed.
        pub passed: bool,
        /// Assertion message recorded by the runtime.
        pub message: String,
        /// Human-readable source location for the assertion.
        pub location: String,
    }

    /// One strict-check failure with a source-relative primary location.
    pub struct ScriptCheckError {}

    /// Error details reported by the script runtime.
    pub struct ScriptErrorInfo {
        #[serde(rename = "type")]
        /// Broad error category such as `parse`, `runtime`, or `assertion`.
        pub error_type: String,
        /// Error message presented to the caller.
        pub message: String,
        #[serde(skip_serializing_if = "Option::is_none")]
        /// Optional source location for the error.
        pub location: Option<ScriptLocation>,
        #[serde(skip_serializing_if = "Option::is_none")]
        /// Optional backtrace rendered by the script runtime.
        pub backtrace: Option<Vec<String>>,
        #[serde(skip_serializing_if = "Option::is_none")]
        /// Optional machine-readable error code for structured tool failures.
        pub code: Option<String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        /// Optional extra error details supplied by the runtime.
        pub details: Option<serde_json::Value>,
    }

    /// Options for evaluating a Luau script.
    pub struct ScriptEvalOptions {
        /// Optional source name used in diagnostics and error messages.
        pub source_name: Option<String>,
        #[serde(default)]
        /// Optional JSON object exposed to the script as the global `args` table.
        pub args: ScriptArgs,
        #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
        /// Named Luau modules available to this script and its dependencies.
        pub modules: ScriptModules,
    }

    /// Structured result of evaluating a Luau script directly against a `DevMcp`
    /// instance.
    pub struct ScriptEvalOutcome {
        /// Whether evaluation completed successfully.
        pub success: bool,
        #[serde(skip_serializing_if = "Option::is_none")]
        /// Optional JSON-serializable script return value.
        pub value: Option<serde_json::Value>,
        #[serde(skip_serializing_if = "Option::is_none")]
        /// Optional metadata for images returned by the script.
        pub images: Option<Vec<ScriptImageInfo>>,
        #[serde(skip_serializing_if = "Vec::is_empty")]
        #[serde(default)]
        /// Log lines emitted through the script `log(...)` helper.
        pub logs: Vec<String>,
        #[serde(skip_serializing_if = "Vec::is_empty")]
        #[serde(default)]
        /// Assertion outcomes recorded during evaluation.
        pub assertions: Vec<ScriptAssertion>,
        #[serde(skip_serializing_if = "Vec::is_empty")]
        #[serde(default)]
        /// Fixtures applied during evaluation.
        pub fixtures: Vec<FixtureApplication>,
        /// Timing information for the evaluation.
        pub timing: ScriptTiming,
        #[serde(skip_serializing_if = "Option::is_none")]
        /// Error details when evaluation fails.
        pub error: Option<ScriptErrorInfo>,
        #[serde(default)]
        #[serde(skip_serializing_if = "EguiDiagnosticBatch::is_empty")]
        /// Undismissed egui identity diagnostics produced during evaluation.
        pub egui_diagnostics: crate::EguiDiagnosticBatch,
    }

    /// Request payload for the `script_eval` MCP tool.
    pub struct ScriptEvalRequest {
        /// Luau source code to execute.
        pub script: String,
        #[serde(skip_serializing_if = "Option::is_none")]
        /// Optional evaluation timeout in milliseconds.
        pub timeout_ms: Option<u64>,
        #[serde(skip_serializing_if = "Option::is_none")]
        /// Optional extra evaluation options.
        pub options: Option<ScriptEvalOptions>,
    }

    /// Metadata for an image captured during script execution.
    pub struct ScriptImageInfo {
        /// Stable image identifier assigned by the runtime.
        pub id: String,
        /// Index of the image content block in the MCP result payload.
        pub content_index: usize,
        /// Image kind such as `viewport` or `widget`.
        pub kind: String,
        #[serde(skip_serializing_if = "Option::is_none")]
        /// Viewport that produced the image when known.
        pub viewport_id: Option<String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        /// Serialized widget target metadata when the image came from a widget.
        pub target: Option<serde_json::Value>,
        #[serde(skip_serializing_if = "Option::is_none")]
        /// Captured rectangle metadata when available.
        pub rect: Option<serde_json::Value>,
        #[serde(skip_serializing_if = "Option::is_none")]
        /// Extra metadata attached by the runtime.
        pub metadata: Option<serde_json::Value>,
    }

    /// Source location reported for a script error.
    pub struct ScriptLocation {
        /// One-based line number.
        pub line: usize,
        #[serde(skip_serializing_if = "Option::is_none")]
        /// One-based column number when available.
        pub column: Option<usize>,
    }

    /// Named Luau module sources available through `require` during one evaluation.
    ///
    /// Keys are portable module paths relative to the caller-selected module root.
    /// A `.luau` suffix is optional for `require`; retaining it here keeps source
    /// names useful in diagnostics and failure bundles.
    pub type ScriptModules = std::collections::BTreeMap<String, String>;

    /// Timing information for a script evaluation.
    pub struct ScriptTiming {
        /// Time spent compiling the script in milliseconds.
        pub compile_ms: u64,
        /// Time spent executing the script in milliseconds.
        pub exec_ms: u64,
        /// Total wall-clock evaluation time in milliseconds.
        pub total_ms: u64,
    }

    pub use eguidev::ScrollAreaMeta;
    #[doc(hidden)]
    /// Optional loopback address used for a directly connectable app MCP server.
    pub const MCP_ADDR_ENV: &str = "EGUIDEV_MCP_ADDR";

    /// Attach the embedded runtime to an inert `DevMcp` handle.
    pub fn attach(devmcp: crate::DevMcp) -> crate::DevMcp {}

    /// Return whether this process was launched for Eguidev automation.
    pub fn automation_launch() -> bool {}

    /// Check one tenant source against the exact checked-in public declaration.
    pub fn check_script_source(source_name: &str, source: &str) -> Result<(), CheckFailure> {}

    /// Keep a background-launched app from taking focus for its whole run.
    ///
    /// On macOS this enables the activation guard: while the automation
    /// presentation is background (the default), any activation of the app that
    /// was not caused by a user mouse interaction is immediately handed back to
    /// the previously frontmost application. Call before the app's event loop
    /// starts. On other platforms this is a no-op.
    pub fn enable_background_launch_guard() {}

    /// Evaluate a Luau script directly against this attached `DevMcp` instance.
    pub async fn eval_script(
        devmcp: &crate::DevMcp,
        script_source: &str,
        timeout_ms: Option<u64>,
        options: crate::ScriptEvalOptions,
    ) -> crate::ScriptEvalOutcome {
    }

    /// Return the checked-in Luau definitions that describe the scripting API.
    pub fn script_definitions() -> &'static str {}

    impl Clone for EguiDiagnostic {
        fn clone(&self) -> EguiDiagnostic {}
    }

    impl Debug for EguiDiagnostic {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl JsonSchema for EguiDiagnostic {
        fn inline_schema() -> bool {}

        fn json_schema(generator: &mut schemars::SchemaGenerator) -> schemars::Schema {}

        fn schema_id() -> schemars::_private::alloc::borrow::Cow<'static, str> {}

        fn schema_name() -> schemars::_private::alloc::borrow::Cow<'static, str> {}
    }

    impl PartialEq for EguiDiagnostic {
        fn eq(&self, other: &EguiDiagnostic) -> bool {}
    }

    impl Serialize for EguiDiagnostic {
        fn serialize<__S>(
            &self,
            __serializer: __S,
        ) -> _serde::__private229::Result<__S::Ok, __S::Error>
        where
            __S: _serde::Serializer, {
        }
    }

    impl<'de> Deserialize<'de> for EguiDiagnostic {
        fn deserialize<__D>(__deserializer: __D) -> _serde::__private229::Result<Self, __D::Error>
        where
            __D: _serde::Deserializer<'de>, {
        }
    }

    impl Clone for EguiDiagnosticBatch {
        fn clone(&self) -> EguiDiagnosticBatch {}
    }

    impl Debug for EguiDiagnosticBatch {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Default for EguiDiagnosticBatch {
        fn default() -> EguiDiagnosticBatch {}
    }

    impl EguiDiagnosticBatch {
        /// Return whether the batch contains no retained or dropped diagnostics.
        pub fn is_empty(&self) -> bool {}
    }

    impl JsonSchema for EguiDiagnosticBatch {
        fn inline_schema() -> bool {}

        fn json_schema(generator: &mut schemars::SchemaGenerator) -> schemars::Schema {}

        fn schema_id() -> schemars::_private::alloc::borrow::Cow<'static, str> {}

        fn schema_name() -> schemars::_private::alloc::borrow::Cow<'static, str> {}
    }

    impl PartialEq for EguiDiagnosticBatch {
        fn eq(&self, other: &EguiDiagnosticBatch) -> bool {}
    }

    impl Serialize for EguiDiagnosticBatch {
        fn serialize<__S>(
            &self,
            __serializer: __S,
        ) -> _serde::__private229::Result<__S::Ok, __S::Error>
        where
            __S: _serde::Serializer, {
        }
    }

    impl<'de> Deserialize<'de> for EguiDiagnosticBatch {
        fn deserialize<__D>(__deserializer: __D) -> _serde::__private229::Result<Self, __D::Error>
        where
            __D: _serde::Deserializer<'de>, {
        }
    }

    impl Clone for EguiDiagnosticKind {
        fn clone(&self) -> EguiDiagnosticKind {}
    }

    impl Debug for EguiDiagnosticKind {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Eq for EguiDiagnosticKind {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl JsonSchema for EguiDiagnosticKind {
        fn inline_schema() -> bool {}

        fn json_schema(generator: &mut schemars::SchemaGenerator) -> schemars::Schema {}

        fn schema_id() -> schemars::_private::alloc::borrow::Cow<'static, str> {}

        fn schema_name() -> schemars::_private::alloc::borrow::Cow<'static, str> {}
    }

    impl PartialEq for EguiDiagnosticKind {
        fn eq(&self, other: &EguiDiagnosticKind) -> bool {}
    }

    impl Serialize for EguiDiagnosticKind {
        fn serialize<__S>(
            &self,
            __serializer: __S,
        ) -> _serde::__private229::Result<__S::Ok, __S::Error>
        where
            __S: _serde::Serializer, {
        }
    }

    impl<'de> Deserialize<'de> for EguiDiagnosticKind {
        fn deserialize<__D>(__deserializer: __D) -> _serde::__private229::Result<Self, __D::Error>
        where
            __D: _serde::Deserializer<'de>, {
        }
    }

    impl Clone for EguiDiagnosticSeverity {
        fn clone(&self) -> EguiDiagnosticSeverity {}
    }

    impl Debug for EguiDiagnosticSeverity {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Eq for EguiDiagnosticSeverity {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl JsonSchema for EguiDiagnosticSeverity {
        fn inline_schema() -> bool {}

        fn json_schema(generator: &mut schemars::SchemaGenerator) -> schemars::Schema {}

        fn schema_id() -> schemars::_private::alloc::borrow::Cow<'static, str> {}

        fn schema_name() -> schemars::_private::alloc::borrow::Cow<'static, str> {}
    }

    impl PartialEq for EguiDiagnosticSeverity {
        fn eq(&self, other: &EguiDiagnosticSeverity) -> bool {}
    }

    impl Serialize for EguiDiagnosticSeverity {
        fn serialize<__S>(
            &self,
            __serializer: __S,
        ) -> _serde::__private229::Result<__S::Ok, __S::Error>
        where
            __S: _serde::Serializer, {
        }
    }

    impl<'de> Deserialize<'de> for EguiDiagnosticSeverity {
        fn deserialize<__D>(__deserializer: __D) -> _serde::__private229::Result<Self, __D::Error>
        where
            __D: _serde::Deserializer<'de>, {
        }
    }

    impl Clone for FixtureApplication {
        fn clone(&self) -> FixtureApplication {}
    }

    impl Debug for FixtureApplication {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl PartialEq for FixtureApplication {
        fn eq(&self, other: &FixtureApplication) -> bool {}
    }

    impl Serialize for FixtureApplication {
        fn serialize<__S>(
            &self,
            __serializer: __S,
        ) -> _serde::__private229::Result<__S::Ok, __S::Error>
        where
            __S: _serde::Serializer, {
        }
    }

    impl<'de> Deserialize<'de> for FixtureApplication {
        fn deserialize<__D>(__deserializer: __D) -> _serde::__private229::Result<Self, __D::Error>
        where
            __D: _serde::Deserializer<'de>, {
        }
    }

    impl Clone for ScriptArgValue {
        fn clone(&self) -> ScriptArgValue {}
    }

    impl Debug for ScriptArgValue {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl JsonSchema for ScriptArgValue {
        fn inline_schema() -> bool {}

        fn json_schema(generator: &mut schemars::SchemaGenerator) -> schemars::Schema {}

        fn schema_id() -> schemars::_private::alloc::borrow::Cow<'static, str> {}

        fn schema_name() -> schemars::_private::alloc::borrow::Cow<'static, str> {}
    }

    impl PartialEq for ScriptArgValue {
        fn eq(&self, other: &ScriptArgValue) -> bool {}
    }

    impl Serialize for ScriptArgValue {
        fn serialize<__S>(
            &self,
            __serializer: __S,
        ) -> _serde::__private229::Result<__S::Ok, __S::Error>
        where
            __S: _serde::Serializer, {
        }
    }

    impl<'de> Deserialize<'de> for ScriptArgValue {
        fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
        where
            D: Deserializer<'de>, {
        }
    }

    impl Clone for ScriptAssertion {
        fn clone(&self) -> ScriptAssertion {}
    }

    impl Debug for ScriptAssertion {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Eq for ScriptAssertion {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl PartialEq for ScriptAssertion {
        fn eq(&self, other: &ScriptAssertion) -> bool {}
    }

    impl Serialize for ScriptAssertion {
        fn serialize<__S>(
            &self,
            __serializer: __S,
        ) -> _serde::__private229::Result<__S::Ok, __S::Error>
        where
            __S: _serde::Serializer, {
        }
    }

    impl<'de> Deserialize<'de> for ScriptAssertion {
        fn deserialize<__D>(__deserializer: __D) -> _serde::__private229::Result<Self, __D::Error>
        where
            __D: _serde::Deserializer<'de>, {
        }
    }

    impl Clone for ScriptCheckError {
        fn clone(&self) -> CheckFailure {}
    }

    impl Debug for ScriptCheckError {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Display for ScriptCheckError {
        fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Eq for ScriptCheckError {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl PartialEq for ScriptCheckError {
        fn eq(&self, other: &CheckFailure) -> bool {}
    }

    impl Clone for ScriptErrorInfo {
        fn clone(&self) -> ScriptErrorInfo {}
    }

    impl Debug for ScriptErrorInfo {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl PartialEq for ScriptErrorInfo {
        fn eq(&self, other: &ScriptErrorInfo) -> bool {}
    }

    impl Serialize for ScriptErrorInfo {
        fn serialize<__S>(
            &self,
            __serializer: __S,
        ) -> _serde::__private229::Result<__S::Ok, __S::Error>
        where
            __S: _serde::Serializer, {
        }
    }

    impl<'de> Deserialize<'de> for ScriptErrorInfo {
        fn deserialize<__D>(__deserializer: __D) -> _serde::__private229::Result<Self, __D::Error>
        where
            __D: _serde::Deserializer<'de>, {
        }
    }

    impl Clone for ScriptEvalOptions {
        fn clone(&self) -> ScriptEvalOptions {}
    }

    impl Debug for ScriptEvalOptions {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Default for ScriptEvalOptions {
        fn default() -> ScriptEvalOptions {}
    }

    impl JsonSchema for ScriptEvalOptions {
        fn inline_schema() -> bool {}

        fn json_schema(generator: &mut schemars::SchemaGenerator) -> schemars::Schema {}

        fn schema_id() -> schemars::_private::alloc::borrow::Cow<'static, str> {}

        fn schema_name() -> schemars::_private::alloc::borrow::Cow<'static, str> {}
    }

    impl PartialEq for ScriptEvalOptions {
        fn eq(&self, other: &ScriptEvalOptions) -> bool {}
    }

    impl Serialize for ScriptEvalOptions {
        fn serialize<__S>(
            &self,
            __serializer: __S,
        ) -> _serde::__private229::Result<__S::Ok, __S::Error>
        where
            __S: _serde::Serializer, {
        }
    }

    impl<'de> Deserialize<'de> for ScriptEvalOptions {
        fn deserialize<__D>(__deserializer: __D) -> _serde::__private229::Result<Self, __D::Error>
        where
            __D: _serde::Deserializer<'de>, {
        }
    }

    impl Clone for ScriptEvalOutcome {
        fn clone(&self) -> ScriptEvalOutcome {}
    }

    impl Debug for ScriptEvalOutcome {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl From<ScriptEvalOutcome> for tmcp::schema::CallToolResult {
        fn from(outcome: ScriptEvalOutcome) -> Self {}
    }

    impl Serialize for ScriptEvalOutcome {
        fn serialize<__S>(
            &self,
            __serializer: __S,
        ) -> _serde::__private229::Result<__S::Ok, __S::Error>
        where
            __S: _serde::Serializer, {
        }
    }

    impl<'de> Deserialize<'de> for ScriptEvalOutcome {
        fn deserialize<__D>(__deserializer: __D) -> _serde::__private229::Result<Self, __D::Error>
        where
            __D: _serde::Deserializer<'de>, {
        }
    }

    impl Clone for ScriptEvalRequest {
        fn clone(&self) -> ScriptEvalRequest {}
    }

    impl Debug for ScriptEvalRequest {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl JsonSchema for ScriptEvalRequest {
        fn inline_schema() -> bool {}

        fn json_schema(generator: &mut schemars::SchemaGenerator) -> schemars::Schema {}

        fn schema_id() -> schemars::_private::alloc::borrow::Cow<'static, str> {}

        fn schema_name() -> schemars::_private::alloc::borrow::Cow<'static, str> {}
    }

    impl PartialEq for ScriptEvalRequest {
        fn eq(&self, other: &ScriptEvalRequest) -> bool {}
    }

    impl Serialize for ScriptEvalRequest {
        fn serialize<__S>(
            &self,
            __serializer: __S,
        ) -> _serde::__private229::Result<__S::Ok, __S::Error>
        where
            __S: _serde::Serializer, {
        }
    }

    impl<'de> Deserialize<'de> for ScriptEvalRequest {
        fn deserialize<__D>(__deserializer: __D) -> _serde::__private229::Result<Self, __D::Error>
        where
            __D: _serde::Deserializer<'de>, {
        }
    }

    impl Clone for ScriptImageInfo {
        fn clone(&self) -> ScriptImageInfo {}
    }

    impl Debug for ScriptImageInfo {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl PartialEq for ScriptImageInfo {
        fn eq(&self, other: &ScriptImageInfo) -> bool {}
    }

    impl Serialize for ScriptImageInfo {
        fn serialize<__S>(
            &self,
            __serializer: __S,
        ) -> _serde::__private229::Result<__S::Ok, __S::Error>
        where
            __S: _serde::Serializer, {
        }
    }

    impl<'de> Deserialize<'de> for ScriptImageInfo {
        fn deserialize<__D>(__deserializer: __D) -> _serde::__private229::Result<Self, __D::Error>
        where
            __D: _serde::Deserializer<'de>, {
        }
    }

    impl Clone for ScriptLocation {
        fn clone(&self) -> ScriptLocation {}
    }

    impl Debug for ScriptLocation {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Eq for ScriptLocation {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl PartialEq for ScriptLocation {
        fn eq(&self, other: &ScriptLocation) -> bool {}
    }

    impl Serialize for ScriptLocation {
        fn serialize<__S>(
            &self,
            __serializer: __S,
        ) -> _serde::__private229::Result<__S::Ok, __S::Error>
        where
            __S: _serde::Serializer, {
        }
    }

    impl<'de> Deserialize<'de> for ScriptLocation {
        fn deserialize<__D>(__deserializer: __D) -> _serde::__private229::Result<Self, __D::Error>
        where
            __D: _serde::Deserializer<'de>, {
        }
    }

    impl Clone for ScriptTiming {
        fn clone(&self) -> ScriptTiming {}
    }

    impl Debug for ScriptTiming {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Eq for ScriptTiming {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl PartialEq for ScriptTiming {
        fn eq(&self, other: &ScriptTiming) -> bool {}
    }

    impl Serialize for ScriptTiming {
        fn serialize<__S>(
            &self,
            __serializer: __S,
        ) -> _serde::__private229::Result<__S::Ok, __S::Error>
        where
            __S: _serde::Serializer, {
        }
    }

    impl<'de> Deserialize<'de> for ScriptTiming {
        fn deserialize<__D>(__deserializer: __D) -> _serde::__private229::Result<Self, __D::Error>
        where
            __D: _serde::Deserializer<'de>, {
        }
    }
}
